(load "lisp/common/core.lisp")
(in-package :maw-tools)
(defparameter *mod* "the_four_primitives_and_weapons")
(defparameter *colors* '( ("指定しない" . nil) ("桜色" . #xE8A6C4) ("白" . #xFFFFFF)
  ("黒" . #x25252B) ("青" . #x278EDE) ("金" . #xEBC55D) ("灰茶" . #x81766B) ("灰緑" . #x747B73)))
(defparameter *weapons* '(("鉄の刀" . "iron_katana") ("鉄の直刀" . "iron_tyokuto")
 ("魔法刀" . "magical_katana") ("上腕骨刀" . "katana_nigu_humerus") ("金の刀" . "gold_katana")
 ("ダイヤの刀" . "diamond_katana") ("ネザライトの刀" . "netherite_katana")
 ("忍者刀" . "ninjatou") ("小太刀" . "small_sword") ("鉄の剣" . "minecraft:iron_sword")))
(defun pick-color (label)
  (let ((i (choose label (append (mapcar #'car *colors*) '("RGB入力 #RRGGBB")))))
    (if (< i (length *colors*)) (cdr (nth i *colors*))
      (loop for s = (prompt "RGB" "#E8A6C4")
            for hex = (cond ((and (> (length s) 0) (char= (char s 0) #\#)) (subseq s 1))
                           ((and (> (length s) 2) (string-equal s "0x" :end1 2)) (subseq s 2)) (t s))
            when (and (= (length hex) 6) (every (lambda (c) (digit-char-p c 16)) hex))
              return (parse-integer hex :radix 16)
            do (format t "6桁のRGBを入力してください。~%")))))
(defun coordinate-valid-p (s)
  (let ((value (string-left-trim "~^" s)))
    (and (<= (+ (count #\~ s) (count #\^ s)) 1)
       (or (member s '("~" "^") :test #'equal)
        (and (> (length value) 0) (every (lambda (c) (find c "-0123456789.")) value)
             (ignore-errors (let ((*read-eval* nil))
               (multiple-value-bind (v end) (read-from-string value)
                 (and (= end (length value)) (realp v) (<= (abs v) 30000000))))))))))
(defun coordinates ()
  (loop for line = (prompt "出現位置 X Y Z" "~ ~1 ~")
        for parts = (uiop:split-string line :separator '(#\Space #\Tab))
        for coords = (remove "" parts :test #'equal)
        when (and (= (length coords) 3) (every #'coordinate-valid-p coords)
                  (or (every (lambda (s) (char= (char s 0) #\^)) coords)
                      (notany (lambda (s) (find #\^ s)) coords)))
          return (format nil "~{~A~^ ~}" coords)
        do (format t "座標を確認してください。~%")))
(defun variant-names ()
  (loop for line in (uiop:split-string (read-text (format nil "src/main/java/~A/entity/ButterflyVariant.java" *mod*)) :separator '(#\Newline))
        for pos = (search "(0x" line)
        when pos collect (string-downcase (string-trim '(#\Space) (subseq line 0 pos)))))
(defun put-colors (tag pairs)
  (loop for (label key) in pairs for value = (pick-color label)
        when value do (setf (gethash key tag) value)))
(defun butterfly-command ()
  (let* ((names (variant-names)) (i (choose "蝶の種類" (cons "ランダム" names))) (tag (object)))
    (when (> i 0) (setf (gethash "Variant" tag) (nth (1- i) names)))
    (when (yes "色と模様を設定しますか？")
      (put-colors tag '(("羽" "WingColor") ("縁" "EdgeColor") ("模様" "AccentColor") ("胴体" "BodyColor")))
      (let ((pattern (choose "模様" '("プリセットのまま" "翅脈" "翅脈と白斑" "アゲハ縞" "小斑点" "目玉" "帯" "点列" "ジグザグ" "輪郭パネル" "市松"))))
        (when (> pattern 0) (setf (gethash "Pattern" tag) (1- pattern))))
      (let ((tails (choose "尾" '("プリセットのまま" "あり" "なし"))))
        (when (> tails 0) (setf (gethash "Tails" tag) (if (= tails 1) :true :false)))))
    (when (yes "大きさ・羽の形・動きを設定しますか？")
      (loop for (label key low high default) in
        '(("大きさ" "Size" 0.25 4 1) ("羽の幅" "WingWidth" 0.5 2 1) ("羽の長さ" "WingLength" 0.5 2 1)
          ("羽ばたき速度" "FlapSpeed" 0 4 1) ("振幅" "FlapAmount" 0 1.4 0.9) ("飛行速度" "FlightSpeed" 0 3 1))
        do (setf (gethash key tag) (numeric label low high default))))
    (when (yes "その場へ固定しますか？")
      (setf (gethash "NoAI" tag) :true (gethash "NoGravity" tag) :true (gethash "PersistenceRequired" tag) :true))
    (if (= 1 (choose "生成方法" '("直接召喚 /summon" "スポーンエッグ /give")))
        (format nil "/give @p ~A:butterfly_spawn_egg~A 1" *mod* (if (plusp (hash-table-count tag)) (encode (object "EntityTag" tag)) ""))
      (let ((name (prompt "名前 (空欄でなし)")))
        (unless (equal name "") (setf (gethash "CustomName" tag) (encode (object "text" name) t)))
        (format nil "/summon ~A:butterfly ~A~A" *mod* (coordinates)
                (if (plusp (hash-table-count tag)) (concatenate 'string " " (encode tag)) ""))))))
(defun item-id ()
  (let* ((i (choose "刀・武器" (append (mapcar #'car *weapons*) '("別のアイテムID"))))
         (item (if (< i (length *weapons*)) (cdr (nth i *weapons*))
                 (loop for s = (prompt "ID" "the_four_primitives_and_weapons:iron_katana")
                       when (and (> (length s) 0) (<= (count #\: s) 1)
                                 (every (lambda (c) (find c "abcdefghijklmnopqrstuvwxyz0123456789_./-:")) s)
                                 (not (char= (char s 0) #\:)) (not (char= (char s (1- (length s))) #\:))) return s))))
    (if (find #\: item) item (format nil "~A:~A" *mod* item))))
(defun weapon-command ()
  (let* ((item (item-id)) (mode (choose "生成方法" '("入手 /give" "刺した状態 /summon"))) (tag (object)))
    (when (yes "拵えの色を設定しますか？ (対応モデルのみ)")
      (put-colors tag '(("柄" "TsukaColor") ("鍔" "TsubaColor") ("頭" "KashiraColor") ("はばき" "HabakiColor"))))
    (let ((name (prompt "武器の名前 (空欄でなし)")))
      (unless (equal name "") (setf (gethash "display" tag) (object "Name" (encode (object "text" name "italic" :false) t)))))
    (let ((disappear (if (yes "回収したときに消えますか？") :true :false)))
      (setf (gethash "DisappearOnPickup" tag) disappear)
      (if (= mode 0) (format nil "/give @p ~A~A 1" item (encode tag))
        (progn
          (format t "Yは武器の中心。地表から約1.5ブロック上が目安です。~%")
          (let ((pos (coordinates)) (entity (object "StabItem" (object "id" item "Count" 1 "tag" tag) "DisappearOnPickup" disappear)))
            (loop for (label key low high default) in '(("向き" "StabYaw" -180 180 0) ("傾き" "StabTilt" -180 180 8)
                    ("ひねり" "StabRoll" -180 180 0) ("大きさ" "StabScale" 0.1 5 1))
                  do (setf (gethash key entity) (numeric label low high default)))
            (format nil "/summon ~A:stabbed_weapon ~A ~A" *mod* pos (encode entity))))))))
(defun command-main ()
  (format t "蝶・刀 コマンド生成 / Common Lisp / オフライン対応~%Enterで既定値。Ctrl+Cで終了。~%")
  (let ((*random-state* (make-random-state t)) (commands nil) (folder (format nil "run/generated_commands/~D-~D/" (get-universal-time) (random 1000000000))))
    (loop for kind = (choose "何を生成しますか？" '("蝶" "刀・武器" "終了"))
          until (= kind 2) do
      (let ((command (if (= kind 0) (butterfly-command) (weapon-command))))
        (setf commands (append commands (list command)))
        (write-text (concatenate 'string folder "commands.txt") (format nil "~{~A~%~}" commands))
        (write-text (concatenate 'string folder "command_builder/pack.mcmeta")
                    (encode (object "pack" (object "pack_format" 15 "description" "蝶・刀の生成コマンド")) t))
        (write-text (concatenate 'string folder "command_builder/data/command_builder/functions/generated.mcfunction")
                    (format nil "~{~A~%~}" (mapcar (lambda (s) (subseq s 1)) commands))))
      (format t "~%~A~%保存先: ~A~%" (car (last commands)) folder)
      (format t "長いコマンドはコマンドブロックへ。command_builderをワールドのdatapacksへコピーすると、~%/reload → /function command_builder:generated で今回の全コマンドを実行できます。~%")
      (when (and (probe-file "/usr/bin/pbcopy") (yes "クリップボードにコピーしますか？"))
        (uiop:run-program '("/usr/bin/pbcopy") :input (make-string-input-stream (car (last commands)))))
      (unless (yes "続けて作りますか？") (return)))))
(unless (member "--test" (uiop:command-line-arguments) :test #'equal) (run-tool #'command-main))
