;;; Original synthesized weather loops. SBCL + ffmpeg; no sampled audio.
(require :asdf)
(defpackage :weather-audio (:use :cl))
(in-package :weather-audio)
(defconstant +rate+ 22050)
(defun little-endian (value bytes stream)
  (dotimes (i bytes) (write-byte (ldb (byte 8 (* 8 i)) value) stream)))
(defun ascii (text stream) (map nil (lambda (c) (write-byte (char-code c) stream)) text))
(defun synthesize (kind seed)
  (let ((samples (make-array (* +rate+ 9) :element-type 'double-float))
        (low 0d0) (mid 0d0) (impact 0d0) (state seed))
    (labels ((noise ()
               (setf state (mod (+ (* state 1664525) 1013904223) (expt 2 32)))
               (/ state 4294967296d0)))
      (dotimes (i (length samples))
        (let* ((time (/ i (float +rate+ 1d0))) (n (- (* 2 (noise)) 1))
               (gust (+ .65d0 (* .2d0 (sin (* time 1.4d0))) (* .15d0 (sin (* time 3.1d0))))))
          (incf low (* .012d0 (- n low)))
          (incf mid (* .16d0 (- n mid)))
          (setf (aref samples i)
                (ecase kind
                  (:wind (* (+ (* low 3) (* mid .35d0)) gust))
                  (:sand (* (+ (* low 2) (* mid .65d0) (* n .08d0)) gust))
                  (:hail
                   (when (< (noise) (/ 28d0 +rate+)) (setf impact (+ .15d0 (* .35d0 (noise)))))
                   (setf impact (* impact .975d0))
                   (+ (* low .8d0) (* impact (+ (* n .6d0) (* (sin (* i 1.7d0)) .4d0))))))))))
    (let ((count (* +rate+ 8)))
      (dotimes (i +rate+)
        (let ((fraction (/ i (float +rate+ 1d0))))
          (setf (aref samples i) (+ (* (aref samples (+ count i)) (- 1 fraction))
                                   (* (aref samples i) fraction)))))
      (subseq samples 0 count))))
(defun write-wave (path samples)
  (let ((size (* 2 (length samples))) (peak (loop for value across samples maximize (abs value))))
    (with-open-file (out path :direction :output :if-exists :supersede :element-type '(unsigned-byte 8))
      (ascii "RIFF" out) (little-endian (+ 36 size) 4 out) (ascii "WAVEfmt " out)
      (little-endian 16 4 out) (little-endian 1 2 out) (little-endian 1 2 out)
      (little-endian +rate+ 4 out) (little-endian (* +rate+ 2) 4 out)
      (little-endian 2 2 out) (little-endian 16 2 out) (ascii "data" out) (little-endian size 4 out)
      (loop for value across samples do (little-endian (round (* (/ value peak) 18000)) 2 out)))))
(let* ((arguments (uiop:command-line-arguments))
       (output (uiop:ensure-directory-pathname (or (first arguments) "src/main/resources/assets/the_four_primitives_and_weapons/sounds/weather/")))
       (temporary (uiop:ensure-directory-pathname (string-trim '(#\Newline) (uiop:run-program '("mktemp" "-d") :output :string)))))
  (ensure-directories-exist output)
  (unwind-protect
       (loop for kind in '(:wind :sand :hail) for seed from 8240
             for name = (string-downcase (symbol-name kind))
             for wav = (merge-pathnames "loop.wav" temporary)
             for ogg = (merge-pathnames (concatenate 'string name ".ogg") output)
             do (write-wave wav (synthesize kind seed))
                (uiop:run-program (list "ffmpeg" "-v" "error" "-y" "-i" (namestring wav) "-ac" "2"
                                       "-c:a" "vorbis" "-strict" "-2" "-q:a" "4" (namestring ogg)) :error-output *error-output*)
                (format t "Generated ~A~%" ogg))
    (uiop:delete-directory-tree temporary :validate t :if-does-not-exist :ignore)))
