(load "lisp/common/core.lisp")
(in-package :maw-tools)
(load "lisp/generate/photo-terrain.lisp")
;; Preserve the source pack; generate randomized scenes only inside the exported world.
(defun nbt (kind value) (cons kind value))
(defun nbt-uint (value size out)
  (loop for shift downfrom (* 8 (1- size)) to 0 by 8 do (write-byte (ldb (byte 8 shift) value) out)))
(defun nbt-string (text out)
  (let ((bytes (sb-ext:string-to-octets text :external-format :utf-8)))
    (nbt-uint (length bytes) 2 out) (write-sequence bytes out)))
(defun nbt-payload (kind value out)
  (case kind
    (1 (nbt-uint value 1 out)) (3 (nbt-uint value 4 out)) (4 (nbt-uint value 8 out))
    (8 (nbt-string value out))
    (9 (write-byte (car value) out) (nbt-uint (length (cdr value)) 4 out)
       (map nil (lambda (entry) (nbt-payload (car value) entry out)) (cdr value)))
    (10 (maphash (lambda (key tag) (write-byte (car tag) out) (nbt-string key out) (nbt-payload (car tag) (cdr tag) out)) value)
        (write-byte 0 out))
    (otherwise (error "未対応NBT型"))))
(defun nbt-compound (&rest pairs) (nbt 10 (apply #'object pairs)))
(defun world-data (name seed)
  (let* ((flat (nbt-compound "type" (nbt 8 "minecraft:flat") "settings"
                 (nbt-compound "biome" (nbt 8 "minecraft:plains") "lakes" (nbt 1 0) "features" (nbt 1 0)
                   "structure_overrides" (nbt 9 (cons 8 #()))
                   "layers" (nbt 9 (cons 10 (vector
                     (object "block" (nbt 8 "minecraft:bedrock") "height" (nbt 3 1))
                     (object "block" (nbt 8 "minecraft:dirt") "height" (nbt 3 127))
                     (object "block" (nbt 8 "minecraft:grass_block") "height" (nbt 3 1))))))))
         (dimensions (object "minecraft:overworld" (nbt-compound "type" (nbt 8 "minecraft:overworld") "generator" flat))))
    (dolist (dim '("the_nether" "the_end"))
      (let ((end (equal dim "the_end")))
        (setf (gethash (concatenate 'string "minecraft:" dim) dimensions)
          (nbt-compound "type" (nbt 8 (concatenate 'string "minecraft:" dim)) "generator"
            (nbt-compound "type" (nbt 8 "minecraft:noise") "settings" (nbt 8 (if end "minecraft:end" "minecraft:nether"))
              "biome_source" (if end (nbt-compound "type" (nbt 8 "minecraft:the_end"))
                (nbt-compound "type" (nbt 8 "minecraft:multi_noise") "preset" (nbt 8 "minecraft:nether"))))))))
    (object "Data" (nbt-compound
      "DataVersion" (nbt 3 3465) "version" (nbt 3 19133)
      "Version" (nbt-compound "Id" (nbt 3 3465) "Name" (nbt 8 "1.20.1") "Series" (nbt 8 "main") "Snapshot" (nbt 1 0))
      "LevelName" (nbt 8 name) "GameType" (nbt 3 1) "allowCommands" (nbt 1 1) "hardcore" (nbt 1 0)
      "Difficulty" (nbt 1 0) "initialized" (nbt 1 1)
      "SpawnX" (nbt 3 -24) "SpawnY" (nbt 3 66) "SpawnZ" (nbt 3 23)
      "Time" (nbt 4 0) "DayTime" (nbt 4 12500) "LastPlayed" (nbt 4 (* 1000 (- (get-universal-time) 2208988800)))
      "clearWeatherTime" (nbt 3 1000000) "raining" (nbt 1 0) "thundering" (nbt 1 0)
      "GameRules" (nbt-compound "doDaylightCycle" (nbt 8 "false") "doWeatherCycle" (nbt 8 "false") "doMobSpawning" (nbt 8 "false"))
      "DataPacks" (nbt-compound "Enabled" (nbt 9 (cons 8 #("vanilla" "mod:forge" "mod:the_four_primitives_and_weapons" "file/blade_gallery")))
                                "Disabled" (nbt 9 (cons 8 #())))
      "WorldGenSettings" (nbt-compound "seed" (nbt 4 seed) "generate_features" (nbt 1 0) "bonus_chest" (nbt 1 0)
                                      "dimensions" (nbt 10 dimensions))))))
(defun copy-tree-files (from to)
  (ensure-directories-exist (merge-pathnames "placeholder" to))
  (dolist (file (uiop:directory-files from)) (uiop:copy-file file (merge-pathnames (file-namestring file) to)))
  (dolist (dir (uiop:subdirectories from))
    (copy-tree-files dir (merge-pathnames (make-pathname :directory (list :relative (car (last (pathname-directory dir))))) to))))
(defun photo-main ()
  (let* ((args (uiop:command-line-arguments))
         (options (make-hash-table :test 'equal)))
    (loop while args for key = (pop args) do
      (unless (and (member key '("--world" "--seed" "--zip") :test #'equal) args)
        (error "--world 保存先 / --seed 0〜2147483647 / --zip ZIP保存先"))
      (setf (gethash key options) (pop args)))
    (let* ((seed (if (gethash "--seed" options) (parse-integer (gethash "--seed" options))
                     (random 2147483648 (make-random-state t))))
         (dest (or (gethash "--world" options) (format nil "run/saves/刀の庭園-~D-~D/" (get-universal-time) seed)))
         (world (merge-pathnames (uiop:ensure-directory-pathname dest) (uiop:getcwd)))
         (name (car (last (pathname-directory world))))
         (raw (merge-pathnames "level.nbt" world)) (dat (merge-pathnames "level.dat" world)))
    (unless (<= 0 seed 2147483647) (error "シードは0〜2147483647です"))
    (when (probe-file world) (error "既存ワールドは上書きしません: ~A" world))
    (ensure-directories-exist raw)
    (with-open-file (out raw :direction :output :if-exists :error :element-type '(unsigned-byte 8))
      (write-byte 10 out) (nbt-string "" out) (nbt-payload 10 (world-data name seed) out))
    (unwind-protect (with-open-file (out dat :direction :output :if-exists :error :element-type '(unsigned-byte 8))
                      (uiop:run-program (list "gzip" "-c" (namestring raw)) :output out :element-type '(unsigned-byte 8)))
      (delete-file raw))
    (copy-tree-files (merge-pathnames #P"photography/blade_gallery/" (uiop:getcwd)) (merge-pathnames "datapacks/blade_gallery/" world))
    (generate-photo-terrain (merge-pathnames "datapacks/blade_gallery/" world) seed)
    (uiop:copy-file "photography/README.md" (merge-pathnames "撮影ガイド.md" world))
    (let ((zip (namestring (merge-pathnames (or (gethash "--zip" options) "photography/blade-gallery-world.zip") (uiop:getcwd)))))
      (ensure-directories-exist zip)
      ;; Build a new archive first, so a failed export cannot destroy the previous ZIP.
      (let ((temp (concatenate 'string zip ".new.zip")))
        (when (probe-file temp) (delete-file temp))
        (uiop:with-current-directory ((uiop:pathname-parent-directory-pathname world))
          (uiop:run-program (list "zip" "-qr" temp name)))
        (uiop:rename-file-overwriting-target temp zip)))
    (format t "ワールド: ~A~%地形シード: ~D~%Lisp地形 → datapacks/blade_gallery/data/blade_gallery/functions/random/~%" world seed))))
(unless (member "--test" (uiop:command-line-arguments) :test #'equal) (run-tool #'photo-main))
