(in-package :maw-tools)
;; Lisp -> mcfunction bridge. Coordinates and PRNG are deterministic for a given seed.
(defvar *terrain-seed* 1)
(defvar *terrain-rng* 1)
(defvar *terrain-lines* nil)
(defun terrain-random (limit)
  (setf *terrain-rng* (mod (+ (* *terrain-rng* 1664525) 1013904223) 4294967296))
  (floor (* limit *terrain-rng*) 4294967296))
(defun terrain-hash (x z)
  (/ (mod (* 1103515245 (logxor *terrain-seed* (* x 374761393) (* z 668265263))) 65536) 65535d0))
(defun terrain-noise (x z scale)
  (let* ((u (/ x scale)) (v (/ z scale)) (ix (floor u)) (iz (floor v))
         (fx (- u ix)) (fz (- v iz)) (sx (* fx fx (- 3 (* 2 fx)))) (sz (* fz fz (- 3 (* 2 fz)))))
    (+ (* (- 1 sz) (+ (* (- 1 sx) (terrain-hash ix iz)) (* sx (terrain-hash (1+ ix) iz))))
       (* sz (+ (* (- 1 sx) (terrain-hash ix (1+ iz))) (* sx (terrain-hash (1+ ix) (1+ iz))))))))
(defun terrain-height (x z center)
  (let* ((dx (- x center))
         (edge (min 1d0 (/ (- 48 (max (abs dx) (abs z))) 10d0)))
         (river (* 9 (exp (- (/ (expt (- dx (* 12 (sin (+ (/ z 22d0) (mod *terrain-seed* 17))))) 2) 70d0)))))
         (ridge (* 13 (max 0 (/ (- (- z) 12d0) 36d0))))
         (height (+ 5 (* 11 (- (terrain-noise x z 28d0) 0.5d0))
                    (* 3 (- (terrain-noise x z 9d0) 0.5d0)) ridge (- river))))
    (round (+ 64 (* (max 0 edge) height)))))
(defun terrain-command (control &rest args) (push (apply #'format nil control args) *terrain-lines*))
(defun terrain-block (x y z block) (terrain-command "setblock ~D ~D ~D ~A" x y z block))
(defun terrain-tree (x y z)
  (terrain-command "fill ~D ~D ~D ~D ~D ~D cherry_log[axis=y]" x y z x (+ y 6) z)
  (loop for dx from -4 to 4 do (loop for dz from -4 to 4
    when (<= (+ (* dx dx) (* dz dz)) 20) do
      (terrain-block (+ x dx) (+ y 7 (if (< (+ (abs dx) (abs dz)) 4) 1 0)) (+ z dz) "cherry_leaves[persistent=true]")
      (when (and (> (+ (abs dx) (abs dz)) 4) (< (terrain-random 100) 55))
        (loop for drop from 1 to (+ 2 (terrain-random 3)) do
          (terrain-block (+ x dx) (- (+ y 7) drop) (+ z dz) "cherry_leaves[persistent=true]"))))))
(defun terrain-ruin (x y z)
  (let ((height (+ 9 (terrain-random 13))))
    (loop for dy from 0 below height do
      (loop for dx from -4 to 4 do (loop for dz from -4 to 4
        when (and (or (= (abs dx) 4) (= (abs dz) 4) (zerop (mod dy 5)))
                  (< (terrain-random 100) (- 95 (* 2 dy)))) do
          (terrain-block (+ x dx) (+ y dy) (+ z dz)
            (if (zerop (terrain-random 4)) "cracked_stone_bricks" "gray_concrete")))))))
(defun terrain-scene (scene center seed)
  (let ((*terrain-seed* seed) (*terrain-rng* (mod (+ seed center) 4294967296)) (*terrain-lines* nil)
        (trees nil))
    (terrain-command "kill @e[type=the_four_primitives_and_weapons:stabbed_weapon,tag=blade_gallery.~A]" scene)
    (terrain-command "gamerule doFireTick false")
    (loop for x from (- center 48) below (+ center 48) do
      (loop for z from -48 below 48 for h = (terrain-height x z center) do
        (terrain-command "fill ~D 58 ~D ~D ~D ~D stone" x z x (- h 3) z)
        (terrain-command "fill ~D ~D ~D ~D ~D ~D dirt" x (- h 2) z x (1- h) z)
        (terrain-block x h z (cond ((< h 64) "gravel")
          ((and (member scene '("burned" "battlefield") :test #'equal) (< (terrain-random 100) 65)) "coarse_dirt")
          (t "grass_block")))
        (terrain-command "fill ~D ~D ~D ~D 144 ~D air" x (1+ h) z x z)
        (cond ((< h 64) (terrain-command "fill ~D ~D ~D ~D 64 ~D water" x (1+ h) z x z))
          ((and (> h 64) (< (abs (- x center)) 42) (< (abs z) 42))
            (let ((roll (terrain-random 100)))
              (cond ((and (equal scene "flowers") (< roll 32))
                     (terrain-block x (1+ h) z (nth (min 4 (floor (* 5 (terrain-noise x z 12d0)))) '("pink_tulip" "allium" "oxeye_daisy" "azure_bluet" "cornflower"))))
                    ((< roll 10) (terrain-block x (1+ h) z "grass"))
                    ((< roll 12) (terrain-block x (1+ h) z (if (equal scene "flowers") "azalea" "mossy_cobblestone")))))))))
    ;; Trees and buildings are added after ALL clearing, so adjacent columns cannot erase them.
    (dotimes (i 180)
      (let* ((x (+ center (- (terrain-random 76) 38))) (z (- (terrain-random 76) 38))
             (h (terrain-height x z center)))
        (when (and (> h 64) (< (length trees) (if (equal scene "flowers") 18 5))
                   (every (lambda (p) (> (+ (expt (- x (car p)) 2) (expt (- z (cdr p)) 2)) 100)) trees))
          (push (cons x z) trees)
          (if (equal scene "flowers") (terrain-tree x (1+ h) z)
            (when (member scene '("rubble" "burned") :test #'equal)
              (terrain-command "fill ~D ~D ~D ~D ~D ~D stripped_dark_oak_log" x (1+ h) z x (+ h 5) z))))))
    (when (member scene '("rubble" "burned") :test #'equal)
      (loop for offset in '(-32 -16 0 16 32) do
        (let* ((x (+ center offset)) (z (+ -32 (terrain-random 8)))
               (y (1+ (loop for dx from -4 to 4 maximize
                     (loop for dz from -4 to 4 maximize (terrain-height (+ x dx) (+ z dz) center))))))
          (loop for dx from -4 to 4 do (loop for dz from -4 to 4 do
            (terrain-command "fill ~D ~D ~D ~D ~D ~D stone_bricks"
              (+ x dx) (terrain-height (+ x dx) (+ z dz) center) (+ z dz) (+ x dx) y (+ z dz))))
          (terrain-ruin x y z))))
    (when (member scene '("rubble" "burned" "battlefield") :test #'equal)
      (dotimes (i 65)
        (let* ((x (+ center (- (terrain-random 80) 40))) (z (- (terrain-random 72) 36))
               (y (1+ (terrain-height x z center))))
          (when (> y 65)
            (terrain-block x y z (if (and (equal scene "burned") (zerop (mod i 9)))
              "campfire[lit=true,signal_fire=false]" "mossy_cobblestone"))))))
    (dotimes (i (if (equal scene "battlefield") 42 9))
      (let* ((x (+ center (- (terrain-random 64) 32))) (z (- (terrain-random 56) 28))
             (h (terrain-height x z center))
             (item (if (equal scene "flowers") "the_four_primitives_and_weapons:magical_katana"
                       (nth (terrain-random 3) '("minecraft:iron_sword" "the_four_primitives_and_weapons:iron_katana" "the_four_primitives_and_weapons:iron_tyokuto")))))
        (when (> h 64)
          (terrain-command "summon the_four_primitives_and_weapons:stabbed_weapon ~,1F ~,1F ~,1F {Tags:[\"blade_gallery.~A\"],StabItem:{id:\"~A\",Count:1b,tag:{TsukaColor:8484469,TsubaColor:7501688,KashiraColor:7632245,HabakiColor:~D}},StabTilt:~Df,StabYaw:~Df,StabScale:1f,DisappearOnPickup:1b}"
            (+ x 0.5d0) (+ h 1.1d0) (+ z 0.5d0) scene item (if (equal scene "flowers") #xE8B4C8 #x8A8980) (+ 8 (terrain-random 65)) (terrain-random 360)))))
    (values (nreverse *terrain-lines*) (terrain-height (- center 10) 22 center))))
(defun terrain-write-function (pack path lines)
  (write-text (merge-pathnames (format nil "data/blade_gallery/functions/~A.mcfunction" path) pack)
    (format nil "~{~A~%~}" lines)))
(defun generate-photo-terrain (pack seed)
  (let ((scenes '("rubble" "burned" "battlefield" "flowers")))
    (loop for scene in scenes for center from 128 by 128 for index from 0 do
      (multiple-value-bind (commands camera-y) (terrain-scene scene center seed)
        (let* ((prefix (format nil "random/~A" scene)) (parts (ceiling (length commands) 256)))
          (terrain-write-function pack (format nil "camera/~A" scene)
            (list (format nil "execute in minecraft:overworld run tp @s ~D ~D 22 facing ~D ~D -12" (- center 10) (+ camera-y 3) center (+ camera-y 5))))
          (terrain-write-function pack (format nil "scenes/~A/setup" scene)
            (list (format nil "execute unless data storage blade_gallery:state random_busy run function blade_gallery:~A/start" prefix)))
          (terrain-write-function pack (format nil "~A/start" prefix)
            (list "data modify storage blade_gallery:state random_busy set value 1b"
              (format nil "execute in minecraft:overworld run forceload add ~D -48 ~D 47" (- center 48) (+ center 47))
              (format nil "schedule function blade_gallery:~A/wait 1s replace" prefix)))
          (terrain-write-function pack (format nil "~A/wait" prefix)
            (list (format nil "schedule function blade_gallery:~A/wait 1s replace" prefix)
              (format nil "execute in minecraft:overworld ~A run function blade_gallery:~A/ready"
                (format nil "~{~A~^ ~}" (loop for x from (- center 48) below (+ center 48) by 16 append
                  (loop for z from -48 below 48 by 16 collect (format nil "if loaded ~D 64 ~D" x z)))) prefix)))
          (terrain-write-function pack (format nil "~A/ready" prefix)
            (list (format nil "schedule clear blade_gallery:~A/wait" prefix)
                  (format nil "execute in minecraft:overworld run function blade_gallery:~A/part_0" prefix)))
          (loop for part below parts for begin = (* part 256) do
            (terrain-write-function pack (format nil "~A/part_~D" prefix part)
              (append (mapcar (lambda (cmd) (concatenate 'string "execute in minecraft:overworld run " cmd))
                             (subseq commands begin (min (length commands) (+ begin 256))))
                (if (< (1+ part) parts)
                  (list (format nil "schedule function blade_gallery:~A/part_~D 1t replace" prefix (1+ part)))
                  (list (format nil "execute in minecraft:overworld run forceload remove ~D -48 ~D 47" (- center 48) (+ center 47))
                    (format nil "tellraw @a {\"text\":\"撮影エリア ~A の生成が完了しました\",\"color\":\"green\"}" scene)
                    "data remove storage blade_gallery:state random_busy"
                    (if (< index 3)
                      (format nil "execute if data storage blade_gallery:state random_all run function blade_gallery:random/~A/start" (nth (1+ index) scenes))
                      (format nil "execute if data storage blade_gallery:state random_all run data modify storage blade_gallery:state random_seed set value ~D" seed))
                    (if (= index 3) "data remove storage blade_gallery:state random_all" "# Next scene continues only during full generation.")))))))))
    (terrain-write-function pack "random/setup" (list
      "execute unless data storage blade_gallery:state random_busy run function blade_gallery:random/start"))
    (terrain-write-function pack "random/start" (list "data modify storage blade_gallery:state random_all set value 1b"
      "function blade_gallery:random/rubble/start"))
    (terrain-write-function pack "scenes/setup" '("function blade_gallery:random/setup"))
    (terrain-write-function pack "scenes/load" (list
      (format nil "execute unless data storage blade_gallery:state {random_seed:~D} run function blade_gallery:random/setup" seed)))
    (write-text (merge-pathnames "terrain-seed.txt" pack) (format nil "~D~%" seed))))
