(load "lisp/common/core.lisp")
(in-package :maw-tools)
(defparameter *moon-benefits*
  '(("jade" "緑（翡翠）" "作物の自然成長を促進。明るさ・土などの条件は必要")
    ("blue" "青" "釣りの抽選だけ幸運+2。宝には開けた水面が必要")
    ("gold" "金" "採掘経験値1.5倍（切り上げ）。元が0なら増えません")
    ("violet" "紫" "プレイヤーの道具・武器・防具の耐久消費を25%の確率で免除")
    ("rose" "桃" "繁殖成立時に親2匹の次回繁殖までの待ち時間を半減")
    ("blood" "Blood Moon" "赤い月の表示のみ。色による追加効果なし")
    ("normal" "白" "色による追加効果なし")))
(defun moon-benefit-description (color)
  (let ((entry (assoc color *moon-benefits* :test #'equal)))
    (if entry (format nil "~A: ~A" (second entry) (third entry)) "自然周期に従う月の色")))
(defun sky-notices (time phase color effects daylight)
  (append
    (when (equal effects "off") '("色のゲーム効果はOFFです。見た目だけ変わります。"))
    (when (and (equal effects "on") (or (< (mod time 24000) 13000) (> (mod time 24000) 23000)))
      '("指定時刻は効果の時間外です。夜（13000〜23000）に有効になります。"))
    (when (and (equal effects "on")
               (= (if (equal phase "auto") (mod (floor time 24000) 8) (parse-integer phase)) 4))
      '("新月では月が見えず、色のゲーム効果も無効です。"))
    (when (member color '("blood" "normal") :test #'equal)
      '("この色には追加のゲーム効果がありません。"))
    (when (equal daylight "false") '("時間停止中は流星の動きと自然周期の日食・月食の進行も止まります。"))))
(defun save-sky-commands (commands)
  (let ((folder (format nil "run/generated_commands/astronomy-~D-~D/" (get-universal-time) (random 1000000000))))
    (write-text (concatenate 'string folder "commands.txt") (format nil "~{~A~%~}" commands))
    (write-text (concatenate 'string folder "generated.mcfunction")
                (format nil "~{~A~%~}" (mapcar (lambda (s) (subseq s 1)) commands)))
    (format t "~%ゲーム内で上から順に実行してください（自動送信はしません）。~%~{~A~%~}~%保存先: ~A~%" commands folder)
    (format t "自然周期へ戻す: /astronomy reset~%日時・天候・時間の進行はresetでは戻りません。~%")))
(defun moon-trial-commands (color)
  (sky-commands 18000 "1.0" "0" color "off" "on" "true" t "off" "off"))
(defun moon-trial ()
  (let* ((index (choose "試す月の効果" (mapcar (lambda (entry) (moon-benefit-description (first entry))) *moon-benefits*)))
         (color (first (nth index *moon-benefits*))))
    (format t "~%~A~%夜・満月・晴れ・効果ONに設定します。流星と食はOFF、時間は進めます。~%ポーション効果は付与しません。~%"
            (moon-benefit-description color))
    (save-sky-commands (moon-trial-commands color))))
(defparameter *sky-presets*
  '(("通常の満月・スーパームーン" . 18000) ("マイクロムーン・金色" . 402000)
    ("ブルームーン" . 210000) ("ブラッドムーン" . 594000)
    ("ジェイドムーン（翡翠色）" . 786000) ("バイオレットムーン" . 1362000)
    ("ローズムーン" . 2898000) ("流星群" . 186000)
    ("日食開始" . 292000) ("日食最大" . 294000)
    ("月食開始" . 1168000) ("月食最大" . 1170000)))
(defun sky-commands (time size phase color meteors effects daylight clear &optional (solar "auto") (lunar "auto") climate)
  (append (when (and clear (not climate)) '("/weather clear"))
    (when climate (list (format nil "/weather ~A" climate)))
    (list (format nil "/time set ~D" time)
          (format nil "/astronomy moon size ~A" size)
          (format nil "/astronomy moon phase ~A" phase)
          (format nil "/astronomy moon color ~A" color)
          (format nil "/astronomy meteors ~A" meteors)
          (format nil "/astronomy eclipse solar ~A" solar)
          (format nil "/astronomy eclipse lunar ~A" lunar)
          (format nil "/astronomy effects ~A" effects)
          (format nil "/gamerule doDaylightCycle ~A" daylight))))
(defun sky-time ()
  (let ((index (choose "時刻・現象" (append (mapcar #'car *sky-presets*) '("tickを直接指定")))))
    (if (< index (length *sky-presets*)) (cdr (nth index *sky-presets*))
      (loop for value = (ignore-errors (parse-integer (prompt "tick (0〜2147483647)" "18000")))
            when (and value (<= 0 value 2147483647)) return value
            do (format t "範囲内の整数を入力してください。~%")))))
(defun sky-eclipse (label)
  (let ((choice (choose label '("自然周期" "有効（最大の状態を維持）" "無効" "0〜1で指定"))))
    (if (= choice 3) (format nil "~,2F" (numeric "値" 0 1 0.5))
      (nth choice '("auto" "on" "off")))))
(defun sky-detailed ()
  (format t "天文・timeコマンド生成（オーバーワールド、チート/管理者権限が必要）~%")
  (let* ((time (sky-time))
         (vanilla-index (choose "月のプリセット" '("個別指定・自然周期" "バニラの満月" "バニラの居待月" "バニラの下弦（半月）" "バニラの欠けていく三日月" "バニラの新月" "バニラの三日月" "バニラの上弦（半月）" "バニラの十三夜")))
         (vanilla-phase (when (> vanilla-index 0) (1- vanilla-index)))
         (size-index (choose "月の大きさ" '("自然周期" "小さい 0.8倍" "通常 1倍" "大きい 1.2倍" "倍率を指定") (if vanilla-phase 2 0)))
         (size (if (= size-index 4) (format nil "~,2F" (numeric "倍率" 0.25 4 1.2))
                 (nth size-index '("auto" "0.8" "1.0" "1.2"))))
         (phase-index (choose "月の形（満ち欠け）" '("自然周期" "満月 (0)" "居待月 (1)" "下弦 (2)" "二十三夜 (3)" "新月 (4)" "三日月 (5)" "上弦 (6)" "十三夜 (7)") (if vanilla-phase (1+ vanilla-phase) 0)))
         (phase (if (= phase-index 0) "auto" (write-to-string (1- phase-index))))
         (color (nth (choose "月の色・夜間効果" '("自然周期" "白・効果なし" "青・釣りの幸運+2" "ブラッドムーン・追加効果なし" "金・採掘経験値1.5倍（切り上げ）" "翡翠・作物の成長促進" "紫・25%の確率で耐久消費なし" "ピンク・繁殖待ち時間半減") (if vanilla-phase 1 0))
                     '("auto" "normal" "blue" "blood" "gold" "jade" "violet" "rose")))
         (meteors (nth (choose "流星（明示的に有効にすると昼も表示）" '("自然周期" "流星群を有効" "流星を無効")) '("auto" "on" "off")))
         (solar (sky-eclipse "日食（0:開始、0.5:最大、1:終了。太陽が見える時刻で確認）"))
         (lunar (sky-eclipse "月食（0:通常、1:最も暗い。月が見える時刻で確認）"))
         (effects (nth (choose "月の色の効果" '("有効" "無効（撮影用）")) '("on" "off")))
         (daylight (nth (choose "時間の進行（停止すると流星も止まります）" '("進める" "止める")) '("true" "false")))
         (weather-index (choose "天候（WMO参考分類、バイオーム制限あり）"
            '("晴れにする" "変更しない" "種類を自然周期へ戻す" "霧" "霧雨" "雨" "大雨" "雪" "大雪" "にわか雨" "雷雨" "雷雨と雹" "砂嵐" "地吹雪")))
         (clear (= 0 weather-index))
         (climate (nth weather-index '("clear" nil "auto" "fog" "drizzle" "rain" "heavy_rain" "snow" "heavy_snow" "showers" "thunderstorm" "hail" "sandstorm" "blowing_snow")))
         (commands (sky-commands time size phase color meteors effects daylight clear solar lunar climate)))
    (format t "~%選択した色: ~A~%" (moon-benefit-description color))
    (dolist (notice (sky-notices time phase color effects daylight)) (format t "案内: ~A~%" notice))
    (save-sky-commands commands)
    (format t "色の効果は夜間のみ。新月では効果なし。手動の流星群は昼も表示。日食と月食は見える天体に反映します。~%")))
(defun sky-main ()
  (format t "オーバーワールド用。チート/管理者権限と対応MODが必要です。~%")
  (case (choose "生成方法" '("月の効果をすぐ試す（色を選ぶだけ）" "天文・天候を細かく設定する" "月の効果の説明を読む"))
    (0 (moon-trial))
    (1 (sky-detailed))
    (2 (dolist (entry *moon-benefits*) (format t "~A~%" (moon-benefit-description (first entry))))
       (format t "夜間13000〜23000・新月以外・オーバーワールド・effects onで有効。ポーション効果なし。~%"))))
(defun sky-self-test ()
  (dolist (entry *moon-benefits*)
    (let ((commands (moon-trial-commands (first entry))))
      (assert (member (format nil "/astronomy moon color ~A" (first entry)) commands :test #'equal))
      (dolist (required '("/time set 18000" "/astronomy moon phase 0" "/astronomy effects on" "/gamerule doDaylightCycle true"))
        (assert (member required commands :test #'equal)))))
  (assert (null (sky-notices 18000 "0" "jade" "on" "true")))
  (assert (= 2 (length (sky-notices 6000 "4" "jade" "on" "true"))))
  (assert (= 1 (length (sky-notices 114000 "auto" "blue" "on" "true"))))
  (let ((commands (sky-commands 186000 "2.0" "5" "jade" "on" "off" "true" t)))
    (assert (= (length commands) 10))
    (assert (member "/time set 186000" commands :test #'equal))
    (assert (member "/astronomy moon phase 5" commands :test #'equal))
    (assert (member "/astronomy meteors on" commands :test #'equal))
    (assert (member "/astronomy effects off" commands :test #'equal))
    (assert (equal (car (sky-commands 2147483647 "auto" "auto" "auto" "auto" "on" "false" nil))
                   "/time set 2147483647"))
    (let ((combined (sky-commands 18000 "1.2" "0" "blue" "on" "on" "true" t "on" "on")))
      (assert (member "/astronomy eclipse solar on" combined :test #'equal))
      (assert (member "/astronomy eclipse lunar on" combined :test #'equal)))
    (assert (member "/weather rain" (sky-commands 18000 "auto" "auto" "auto" "auto" "on" "true" nil "auto" "auto" "rain") :test #'equal))
    (assert (member "/weather auto" (sky-commands 18000 "auto" "auto" "auto" "auto" "on" "true" nil "auto" "auto" "auto") :test #'equal))
    (format t "天文コマンド生成のテスト成功~%")))
(run-tool (if (member "--self-test" (uiop:command-line-arguments) :test #'equal) #'sky-self-test #'sky-main))
