modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="minecraft_armor_weapon"
version="1.0.0"
displayName="minecraft armor weapon"
credits="nemui"
displayURL="https://onl.la/6CYtJhQ"
updateJSONURL="https://curseforge.com/minecraft/mc-mods/the-four-primitives-and-weapons/files/all?page=1&pageSize=20"
logoFile="logo.png"
authors="0526ngs"

[[dependencies.minecraft_armor_weapon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




