;;; Run: sbcl --script tests/MisakiFontSpacingTest.lisp
(load (merge-pathnames "../scripts/misaki-font.lisp" *load-truename*))
(in-package :misaki-font)

(let* ((original (read-bytes (merge-pathnames "misaki_gothic.ttf" *pack-font*)))
       (corrected (read-bytes (merge-pathnames "misaki_gothic_minecraft.ttf" *base-font*)))
       (before (tables original))
       (after (tables corrected))
       (metrics (uint original (+ (table-offset (gethash "hhea" before)) 34) 2))
       (old-hmtx (table-offset (gethash "hmtx" before)))
       (new-hmtx (table-offset (gethash "hmtx" after)))
       (changed 0))
  (dotimes (i metrics)
    (assert (= (uint original (+ old-hmtx (* i 4)) 2)
               (uint corrected (+ new-hmtx (* i 4)) 2)) () "Character advance changed")
    (assert (zerop (uint corrected (+ new-hmtx (* i 4) 2) 2)) () "Redundant bearing remains")
    (unless (zerop (uint original (+ old-hmtx (* i 4) 2) 2)) (incf changed)))
  (assert (plusp changed))
  (maphash (lambda (tag old)
             (unless (member tag '("hmtx" "head" "hhea") :test #'equal)
               (let ((new (gethash tag after)))
                 (assert (equalp (subseq original (table-offset old) (+ (table-offset old) (table-length old)))
                                 (subseq corrected (table-offset new) (+ (table-offset new) (table-length new))))
                         () "Unexpected change to table ~A" tag)))) before)
  (let* ((old (table-offset (gethash "hhea" before)))
         (new (table-offset (gethash "hhea" after)))
         (old-ascent (signed16 (uint original (+ old 4) 2)))
         (old-descent (signed16 (uint original (+ old 6) 2)))
         (new-ascent (signed16 (uint corrected (+ new 4) 2)))
         (new-descent (signed16 (uint corrected (+ new 6) 2)))
         (scale (/ 8 (- new-ascent new-descent))))
    (assert (= (- old-ascent old-descent) (- new-ascent new-descent)) () "STB glyph scale changed")
    (assert (= (* (- new-ascent old-ascent) scale) 3) () "Baseline must move down exactly three pixels")
    (assert (= (- (* new-ascent scale) (ceiling (* 1536 scale)) 3) 0)
            () "Full-height Japanese glyph must align with ASCII top")
    (assert (= (- (* new-ascent scale) (ceiling (* 1024 scale)) 3) 2)
            () "Small kana must retain their intended lower position")
    (assert (equalp (subseq original (+ old 8) (+ old (table-length (gethash "hhea" before))))
                    (subseq corrected (+ new 8) (+ new (table-length (gethash "hhea" after)))))
            () "Unrelated horizontal header metrics changed"))
  (assert (= (font-checksum corrected) #xb1b0afba))
  (assert (equalp (fix-font original) corrected) () "Generation is not reproducible")
  (assert (equalp (fix-font corrected) corrected) () "Correction is not idempotent")
  (assert (equalp (read-bytes (merge-pathnames "misaki_gothic_minecraft.ttf" *pack-font*)) corrected))
  (dolist (relative '("src/main/resources/assets/minecraft/font/default.json"
                      "src/main/resources/resourcepacks/misaki_font_pack/assets/minecraft/font/default.json"))
    (with-open-file (stream (merge-pathnames relative *root*))
      (let ((text (make-string (file-length stream))))
        (read-sequence text stream)
        (assert (search "the_four_primitives_and_weapons:misaki_gothic_minecraft.ttf" text)))))
  (format t "MisakiFontSpacingTest passed (~D glyph bearings corrected).~%" changed))
