(require :asdf)
(defpackage :maw-tools (:use :cl))
(in-package :maw-tools)
(defun object (&rest pairs)
  (let ((table (make-hash-table :test 'equal)))
    (loop for (key value) on pairs by #'cddr do (setf (gethash key table) value)) table))
(defun read-text (path) (uiop:read-file-string path :external-format :utf-8))
(defun write-text (path text)
  (ensure-directories-exist path)
  (with-open-file (out path :direction :output :if-exists :supersede :external-format :utf-8)
    (write-string text out)))
(defun quote-text (text &optional json)
  (with-output-to-string (out)
    (write-char #\" out)
    (loop for c across text do
      (case c
        (#\" (write-string "\\\"" out)) (#\\ (write-string "\\\\" out))
        (#\Newline (if json (write-string "\\n" out) (error "制御文字は使えません")))
        (#\Return (if json (write-string "\\r" out) (error "制御文字は使えません")))
        (#\Tab (if json (write-string "\\t" out) (error "制御文字は使えません")))
        (otherwise (if (< (char-code c) 32)
                       (if json (format out "\\u~4,'0X" (char-code c)) (error "制御文字は使えません"))
                       (write-char c out)))))
    (write-char #\" out)))
(defun encode (value &optional (json nil))
  (typecase value
    (hash-table (format nil "{~{~A~^,~}}"
                        (loop for k being the hash-keys of value using (hash-value v)
                              collect (format nil "~A:~A" (if json (quote-text k t) k) (encode v json)))))
    (string (quote-text value json))
    (vector (format nil "[~{~A~^,~}]" (map 'list (lambda (v) (encode v json)) value)))
    (integer (format nil "~D" value))
    (float (let ((s (substitute #\e #\d (string-downcase (format nil "~S" value))))) (if json s (concatenate 'string s "f"))))
    (symbol (ecase value (:true (if json "true" "1b")) (:false (if json "false" "0b")) (:null "null")))
    (t (error "未対応の値 ~S" value))))
(defun parse-json (source)
  (let ((i 0) (n (length source)))
    (labels ((peek () (when (< i n) (char source i)))
             (take () (or (prog1 (peek) (incf i)) (error "JSONの途中で終了")))
             (space () (loop while (and (peek) (find (peek) '(#\Space #\Tab #\Return #\Newline))) do (incf i)))
             (expect (c) (unless (eql (take) c) (error "JSON: ~A が必要" c)))
             (hex4 () (let ((s (subseq source i (+ i 4)))) (incf i 4) (parse-integer s :radix 16)))
             (str () (expect #\")
               (with-output-to-string (out)
                 (loop for c = (take) until (char= c #\") do
                   (if (char= c #\\)
                       (let ((e (take)))
                         (write-char (case e
                           (#\" #\") (#\\ #\\) (#\/ #\/) (#\n #\Newline) (#\r #\Return)
                           (#\t #\Tab) (#\b #\Backspace) (#\f #\Page)
                           (#\u (let ((cp (hex4)))
                                   (when (<= #xD800 cp #xDBFF)
                                     (expect #\\) (expect #\u)
                                     (let ((low (hex4)))
                                       (unless (<= #xDC00 low #xDFFF) (error "不正なサロゲート"))
                                       (setf cp (+ #x10000 (* (- cp #xD800) 1024) (- low #xDC00)))))
                                   (or (code-char cp) (error "不正な文字"))))
                           (otherwise (error "JSONエスケープが不正"))) out))
                       (progn (when (< (char-code c) 32) (error "JSON制御文字")) (write-char c out))))))
             (val () (space)
               (case (peek)
                 (#\" (str))
                 (#\{ (take) (space) (let ((o (object)))
                         (unless (eql (peek) #\})
                           (loop (space) (let ((k (str))) (space) (expect #\:) (setf (gethash k o) (val)))
                                 (space) (if (eql (peek) #\,) (take) (return))))
                         (expect #\}) o))
                 (#\[ (take) (space) (let ((values nil))
                         (unless (eql (peek) #\])
                           (loop (push (val) values) (space) (if (eql (peek) #\,) (take) (return))))
                         (expect #\]) (coerce (nreverse values) 'vector)))
                 (otherwise
                   (let* ((start i) (token (progn
                      (loop while (and (peek) (not (find (peek) '(#\Space #\Tab #\Return #\Newline #\, #\] #\})))) do (incf i))
                      (subseq source start i))))
                     (cond ((equal token "true") :true) ((equal token "false") :false) ((equal token "null") :null)
                           ((and (> (length token) 0) (every (lambda (c) (find c "0123456789+-.eE")) token))
                            (let ((*read-eval* nil) (*read-default-float-format* 'double-float))
                              (multiple-value-bind (v end) (read-from-string token)
                                (unless (and (numberp v) (= end (length token))) (error "不正なJSON数値")) v)))
                           (t (error "不正なJSON値 ~A" token))))))))
      (let ((result (val))) (space) (unless (= i n) (error "JSON末尾に余分なデータ")) result))))
(defun prompt (label &optional (default ""))
  (format t "~A~A: " label (if (equal default "") "" (format nil " [~A]" default)))
  (finish-output)
  (let ((line (read-line *standard-input* nil nil)))
    (unless line (throw 'done nil))
    (let ((s (string-trim '(#\Space #\Tab) line)))
      (if (equal s "") default s))))
(defun choose (label options &optional (default 0))
  (format t "~%~A~%" label)
  (loop for option in options for i from 1 do (format t "  ~D. ~A~%" i option))
  (loop for value = (ignore-errors (parse-integer (prompt "番号" (write-to-string (1+ default)))))
        when (and value (<= 1 value (length options))) return (1- value)
        do (format t "一覧の番号を入力してください。~%")))
(defun yes (label) (= 0 (choose label '("はい" "いいえ") 1)))
(defun numeric (label low high default)
  (loop for s = (prompt (format nil "~A (~A〜~A)" label low high) (format nil "~A" default))
        for value = (ignore-errors
          (when (and (> (length s) 0) (every (lambda (c) (find c "0123456789+-.")) s))
            (let ((*read-eval* nil)) (multiple-value-bind (v end) (read-from-string s)
              (when (and (realp v) (= end (length s)) (<= low v high)) (float v))))))
        when value return value do (format t "範囲内の数値を入力してください。~%")))
(defun run-tool (function)
  (handler-case (catch 'done (funcall function))
    (error (e) (format *error-output* "エラー: ~A~%" e) (uiop:quit 1))))
