
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package the_four_primitives_and_weapons.init;

import org.checkerframework.checker.units.qual.A;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import the_four_primitives_and_weapons.item.WoodenRapierItem;
import the_four_primitives_and_weapons.item.RapierSayaItem;
import the_four_primitives_and_weapons.item.StoneRapierItem;
import the_four_primitives_and_weapons.item.IronRapierItem;
import the_four_primitives_and_weapons.item.GoldRapierItem;
import the_four_primitives_and_weapons.item.DiamondRapierItem;
import the_four_primitives_and_weapons.item.NetheriteRapierItem;
import the_four_primitives_and_weapons.item.ParryShieldItem;
import the_four_primitives_and_weapons.item.OfudaItem;
import the_four_primitives_and_weapons.item.WitherKatanaItem;
import the_four_primitives_and_weapons.item.WitherBoneItem;
import the_four_primitives_and_weapons.item.WindStepItem;
import the_four_primitives_and_weapons.item.WardenArmorItem;
import the_four_primitives_and_weapons.item.WarabitetouItem;
import the_four_primitives_and_weapons.item.TyokutoSayaItem;
import the_four_primitives_and_weapons.item.SwordSayaItem;
import the_four_primitives_and_weapons.item.TukaenaItem;
import the_four_primitives_and_weapons.item.ThunderboltItem;
import the_four_primitives_and_weapons.item.StrayouterarmorhatItem;
import the_four_primitives_and_weapons.item.StrayOuterArmorItem;
import the_four_primitives_and_weapons.item.StrayBoneItem;
import the_four_primitives_and_weapons.item.StormItem;
import the_four_primitives_and_weapons.item.StoneSlabItem;
import the_four_primitives_and_weapons.item.StoneKatanaItem;
import the_four_primitives_and_weapons.item.SmallSwordItem;
import the_four_primitives_and_weapons.item.SkinOfDragonItem;
import the_four_primitives_and_weapons.item.ScytheItem;
import the_four_primitives_and_weapons.item.SayaItem;
import the_four_primitives_and_weapons.item.RiversOfBloodItem;
import the_four_primitives_and_weapons.item.ResetMaxItem;
import the_four_primitives_and_weapons.item.Reset1Item;
import the_four_primitives_and_weapons.item.QuestbookItem;
import the_four_primitives_and_weapons.item.PumpkinHeadItem;
import the_four_primitives_and_weapons.item.ZombieHeartItem;
import the_four_primitives_and_weapons.item.PrototypeKatanaItem;
import the_four_primitives_and_weapons.item.PillagerArmorItem;
import the_four_primitives_and_weapons.item.OninomenItem;
import the_four_primitives_and_weapons.item.OldKatanaItem;
import the_four_primitives_and_weapons.item.NinjatouItem;
import the_four_primitives_and_weapons.item.NiguShieldItem;
import the_four_primitives_and_weapons.item.NetheriteKatanaItem;
import the_four_primitives_and_weapons.item.MyTestIronKatanaItem;

import the_four_primitives_and_weapons.item.MotaseruItem;
import the_four_primitives_and_weapons.item.MagischesFeenKatanaItem;
import the_four_primitives_and_weapons.item.MagicwandItem;
import the_four_primitives_and_weapons.item.MagicalKatanaItem;
import the_four_primitives_and_weapons.item.MagicMcrystalItem;
import the_four_primitives_and_weapons.item.MacheteItem;
import the_four_primitives_and_weapons.item.LunaItem;
import the_four_primitives_and_weapons.item.KurikarakenItem;
import the_four_primitives_and_weapons.item.KentiItem;
import the_four_primitives_and_weapons.item.KatanaTobuItem;
import the_four_primitives_and_weapons.item.KatanaNiguHumerusItem;
import the_four_primitives_and_weapons.item.KabuseruItem;
import the_four_primitives_and_weapons.item.ItemWeaponswordItem;
import the_four_primitives_and_weapons.item.IronKatanaItem;
import the_four_primitives_and_weapons.item.WoodenKatanaItem;
import the_four_primitives_and_weapons.item.WoodenTyokutoItem;
import the_four_primitives_and_weapons.item.DiamondKatanaItem;
import the_four_primitives_and_weapons.item.DiamondTyokutoItem;
import the_four_primitives_and_weapons.item.NetheriteTyokutoItem;
import the_four_primitives_and_weapons.item.ImitationItem;
import the_four_primitives_and_weapons.item.IllusionerArmorItem;
import the_four_primitives_and_weapons.item.HarvestMoon2023929Item;
import the_four_primitives_and_weapons.item.HammerItem;
import the_four_primitives_and_weapons.item.Halloween20231031SickleItem;
import the_four_primitives_and_weapons.item.GoldKatanaItem;
import the_four_primitives_and_weapons.item.FireworksBlackItem;
import the_four_primitives_and_weapons.item.HolyBookItem;
import the_four_primitives_and_weapons.item.IceBookItem;
import the_four_primitives_and_weapons.item.ElectricBookItem;
import the_four_primitives_and_weapons.item.CorrosionBookItem;
import the_four_primitives_and_weapons.item.ReitouItem;
import the_four_primitives_and_weapons.item.ErasureBookItem;
import the_four_primitives_and_weapons.item.MiasmaBookItem;
import the_four_primitives_and_weapons.item.SoulBookItem;
import the_four_primitives_and_weapons.item.SoulFireBookItem;
import the_four_primitives_and_weapons.item.ElementCleansePotionItem;
import the_four_primitives_and_weapons.item.FireballItem;
import the_four_primitives_and_weapons.item.DragonRedArmorItem;
import the_four_primitives_and_weapons.item.DragonGreenArmorItem;
import the_four_primitives_and_weapons.item.DragonBlueArmorItem;
import the_four_primitives_and_weapons.item.DragonBlackArmorItem;
import the_four_primitives_and_weapons.item.DragonArmorItem;
import the_four_primitives_and_weapons.item.CopperArmorItem;
import the_four_primitives_and_weapons.item.DespornKentiItem;
import the_four_primitives_and_weapons.item.DecorationPotWithArrowsItem;
import the_four_primitives_and_weapons.item.DasHerzEinerFeeArmorItem;
import the_four_primitives_and_weapons.item.DarknessKatanaItem;
import the_four_primitives_and_weapons.item.DarknessItem;
import the_four_primitives_and_weapons.item.BubbleshotItem;
import the_four_primitives_and_weapons.item.BoggedOuterItem;
import the_four_primitives_and_weapons.item.BloodBottleItem;
import the_four_primitives_and_weapons.item.ArrowHeadItem;
import the_four_primitives_and_weapons.item.AchromaticShieldItem;
import the_four_primitives_and_weapons.item.AaaItem;
import the_four_primitives_and_weapons.item.AItem;
import the_four_primitives_and_weapons.item.A2Item;

import the_four_primitives_and_weapons.TheFourPrimitivesAndWeaponsMod;

public class TheFourPrimitivesAndWeaponsModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, TheFourPrimitivesAndWeaponsMod.MODID);
	public static final RegistryObject<Item> BUBBLESHOT = REGISTRY.register("bubbles_book", () -> new BubbleshotItem());
	public static final RegistryObject<Item> FIREBALL = REGISTRY.register("fire_book", () -> new FireballItem());
	public static final RegistryObject<Item> THUNDERBOLT = REGISTRY.register("thunder_book", () -> new ThunderboltItem());
	public static final RegistryObject<Item> ITEM_WEAPONSWORD = REGISTRY.register("item_weaponsword", () -> new ItemWeaponswordItem());
	public static final RegistryObject<Item> NETHERITE_KATANA = REGISTRY.register("netherite_katana", () -> new NetheriteKatanaItem());
	public static final RegistryObject<Item> ROSE = block(TheFourPrimitivesAndWeaponsModBlocks.ROSE, null);
	public static final RegistryObject<Item> PILLAGER_ARMOR_HELMET = REGISTRY.register("pillager_armor_helmet", () -> new PillagerArmorItem.Helmet());
	public static final RegistryObject<Item> PILLAGER_ARMOR_CHESTPLATE = REGISTRY.register("pillager_armor_chestplate", () -> new PillagerArmorItem.Chestplate());
	public static final RegistryObject<Item> PILLAGER_ARMOR_LEGGINGS = REGISTRY.register("pillager_armor_leggings", () -> new PillagerArmorItem.Leggings());
	public static final RegistryObject<Item> PILLAGER_ARMOR_BOOTS = REGISTRY.register("pillager_armor_boots", () -> new PillagerArmorItem.Boots());
	public static final RegistryObject<Item> ILLUSIONER_ARMOR_HELMET = REGISTRY.register("illusioner_armor_helmet", () -> new IllusionerArmorItem.Helmet());
	public static final RegistryObject<Item> ILLUSIONER_ARMOR_CHESTPLATE = REGISTRY.register("illusioner_armor_chestplate", () -> new IllusionerArmorItem.Chestplate());
	public static final RegistryObject<Item> ILLUSIONER_ARMOR_LEGGINGS = REGISTRY.register("illusioner_armor_leggings", () -> new IllusionerArmorItem.Leggings());
	public static final RegistryObject<Item> ILLUSIONER_ARMOR_BOOTS = REGISTRY.register("illusioner_armor_boots", () -> new IllusionerArmorItem.Boots());
	public static final RegistryObject<Item> STONE_KATANA = REGISTRY.register("stone_katana", () -> new StoneKatanaItem());
	public static final RegistryObject<Item> A = REGISTRY.register("a", () -> new AItem());
	public static final RegistryObject<Item> HAMMER = REGISTRY.register("hammer", () -> new HammerItem());
	public static final RegistryObject<Item> IRON_KATANA = REGISTRY.register("iron_katana", () -> new IronKatanaItem());
	public static final RegistryObject<Item> WOODEN_KATANA = REGISTRY.register("wooden_katana", () -> new WoodenKatanaItem());
	public static final RegistryObject<Item> WOODEN_TYOKUTO = REGISTRY.register("wooden_tyokuto", () -> new WoodenTyokutoItem());
	public static final RegistryObject<Item> DIAMOND_KATANA = REGISTRY.register("diamond_katana", () -> new DiamondKatanaItem());
	public static final RegistryObject<Item> DIAMOND_TYOKUTO = REGISTRY.register("diamond_tyokuto", () -> new DiamondTyokutoItem());
	public static final RegistryObject<Item> NETHERITE_TYOKUTO = REGISTRY.register("netherite_tyokuto", () -> new NetheriteTyokutoItem());
	public static final RegistryObject<Item> CROSS = block(TheFourPrimitivesAndWeaponsModBlocks.CROSS, TheFourPrimitivesAndWeaponsModTabs.TAB_YOPKEINAMONO);
	public static final RegistryObject<Item> MY_TEST_IRON_KATANA = REGISTRY.register("my_test_iron_katana", () -> new MyTestIronKatanaItem());
	public static final RegistryObject<Item> PROMISE_KATANA = REGISTRY.register("promise_katana", () -> new the_four_primitives_and_weapons.item.PromiseWeaponItem("katana"));
	public static final RegistryObject<Item> PROMISE_SWORD = REGISTRY.register("promise_sword", () -> new the_four_primitives_and_weapons.item.PromiseWeaponItem("sword"));
	public static final RegistryObject<Item> PROMISE_STRAIGHT_SWORD = REGISTRY.register("promise_straight_sword", () -> new the_four_primitives_and_weapons.item.PromiseWeaponItem("straight_sword"));
	public static final RegistryObject<Item> RING = REGISTRY.register("ring", () -> new the_four_primitives_and_weapons.item.RingItem());
	public static final RegistryObject<Item> LUNA = REGISTRY.register("luna", () -> new LunaItem());
	public static final RegistryObject<Item> SKELTON_MOB_SPAWN_EGG = REGISTRY.register("skelton_mob_spawn_egg", () -> new ForgeSpawnEggItem(TheFourPrimitivesAndWeaponsModEntities.SKELTON_MOB, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> ACHROMATIC_SHIELD = REGISTRY.register("achromatic_shield", () -> new AchromaticShieldItem());
	public static final RegistryObject<Item> HARVEST_MOON_2023929 = REGISTRY.register("harvest_moon_2023929", () -> new HarvestMoon2023929Item());
	public static final RegistryObject<Item> WARABITETOU = REGISTRY.register("warabitetou", () -> new WarabitetouItem());
	public static final RegistryObject<Item> A_2 = REGISTRY.register("a_2", () -> new A2Item());
	public static final RegistryObject<Item> WIND_STEP = REGISTRY.register("wind_book", () -> new WindStepItem());
	public static final RegistryObject<Item> STRAY_OUTER_ARMOR_HELMET = REGISTRY.register("stray_outer_armor_helmet", () -> new StrayOuterArmorItem.Helmet());
	public static final RegistryObject<Item> STRAY_OUTER_ARMOR_CHESTPLATE = REGISTRY.register("stray_outer_armor_chestplate", () -> new StrayOuterArmorItem.Chestplate());
	public static final RegistryObject<Item> STRAY_OUTER_ARMOR_LEGGINGS = REGISTRY.register("stray_outer_armor_leggings", () -> new StrayOuterArmorItem.Leggings());
	public static final RegistryObject<Item> STRAYOUTERARMORHAT_HELMET = REGISTRY.register("strayouterarmorhat_helmet", () -> new StrayouterarmorhatItem.Helmet());
	public static final RegistryObject<Item> MAGIC_MCRYSTAL = REGISTRY.register("magic_mcrystal", () -> new MagicMcrystalItem());
	public static final RegistryObject<Item> MAGICAL_KATANA = REGISTRY.register("magical_katana", () -> new MagicalKatanaItem());
	public static final RegistryObject<Item> STONE_BRICKS_TRAP_DOOR = block(TheFourPrimitivesAndWeaponsModBlocks.STONE_BRICKS_TRAP_DOOR, TheFourPrimitivesAndWeaponsModTabs.TAB_YOPKEINAMONO);
	public static final RegistryObject<Item> ROSE_FLOWER_POT = block(TheFourPrimitivesAndWeaponsModBlocks.ROSE_FLOWER_POT, TheFourPrimitivesAndWeaponsModTabs.TAB_MAGIC_BOOKS);
	public static final RegistryObject<Item> HALLOWEEN_2023_10_31_SICKLE = REGISTRY.register("halloween_2023_10_31_sickle", () -> new Halloween20231031SickleItem());
	public static final RegistryObject<Item> KATANA_TOBU = REGISTRY.register("katana_tobu", () -> new KatanaTobuItem());
	public static final RegistryObject<Item> DRAGON_ARMOR_HELMET = REGISTRY.register("dragon_armor_helmet", () -> new DragonArmorItem.Helmet());
	public static final RegistryObject<Item> DRAGON_ARMOR_CHESTPLATE = REGISTRY.register("dragon_armor_chestplate", () -> new DragonArmorItem.Chestplate());
	public static final RegistryObject<Item> DRAGON_ARMOR_LEGGINGS = REGISTRY.register("dragon_armor_leggings", () -> new DragonArmorItem.Leggings());
	public static final RegistryObject<Item> DRAGON_ARMOR_BOOTS = REGISTRY.register("dragon_armor_boots", () -> new DragonArmorItem.Boots());
	public static final RegistryObject<Item> DRAGON_GREEN_ARMOR_HELMET = REGISTRY.register("dragon_green_armor_helmet", () -> new DragonGreenArmorItem.Helmet());
	public static final RegistryObject<Item> DRAGON_GREEN_ARMOR_CHESTPLATE = REGISTRY.register("dragon_green_armor_chestplate", () -> new DragonGreenArmorItem.Chestplate());
	public static final RegistryObject<Item> DRAGON_GREEN_ARMOR_LEGGINGS = REGISTRY.register("dragon_green_armor_leggings", () -> new DragonGreenArmorItem.Leggings());
	public static final RegistryObject<Item> DRAGON_GREEN_ARMOR_BOOTS = REGISTRY.register("dragon_green_armor_boots", () -> new DragonGreenArmorItem.Boots());
	public static final RegistryObject<Item> DRAGON_BLACK_ARMOR_HELMET = REGISTRY.register("dragon_black_armor_helmet", () -> new DragonBlackArmorItem.Helmet());
	public static final RegistryObject<Item> DRAGON_BLACK_ARMOR_CHESTPLATE = REGISTRY.register("dragon_black_armor_chestplate", () -> new DragonBlackArmorItem.Chestplate());
	public static final RegistryObject<Item> DRAGON_BLACK_ARMOR_LEGGINGS = REGISTRY.register("dragon_black_armor_leggings", () -> new DragonBlackArmorItem.Leggings());
	public static final RegistryObject<Item> DRAGON_BLACK_ARMOR_BOOTS = REGISTRY.register("dragon_black_armor_boots", () -> new DragonBlackArmorItem.Boots());
	public static final RegistryObject<Item> DRAGON_RED_ARMOR_HELMET = REGISTRY.register("dragon_red_armor_helmet", () -> new DragonRedArmorItem.Helmet());
	public static final RegistryObject<Item> DRAGON_RED_ARMOR_CHESTPLATE = REGISTRY.register("dragon_red_armor_chestplate", () -> new DragonRedArmorItem.Chestplate());
	public static final RegistryObject<Item> DRAGON_RED_ARMOR_LEGGINGS = REGISTRY.register("dragon_red_armor_leggings", () -> new DragonRedArmorItem.Leggings());
	public static final RegistryObject<Item> DRAGON_RED_ARMOR_BOOTS = REGISTRY.register("dragon_red_armor_boots", () -> new DragonRedArmorItem.Boots());
	public static final RegistryObject<Item> DRAGON_BLUE_ARMOR_HELMET = REGISTRY.register("dragon_blue_armor_helmet", () -> new DragonBlueArmorItem.Helmet());
	public static final RegistryObject<Item> DRAGON_BLUE_ARMOR_CHESTPLATE = REGISTRY.register("dragon_blue_armor_chestplate", () -> new DragonBlueArmorItem.Chestplate());
	public static final RegistryObject<Item> DRAGON_BLUE_ARMOR_LEGGINGS = REGISTRY.register("dragon_blue_armor_leggings", () -> new DragonBlueArmorItem.Leggings());
	public static final RegistryObject<Item> DRAGON_BLUE_ARMOR_BOOTS = REGISTRY.register("dragon_blue_armor_boots", () -> new DragonBlueArmorItem.Boots());
	public static final RegistryObject<Item> COPPER_ARMOR_HELMET = REGISTRY.register("copper_armor_helmet", () -> new CopperArmorItem.Helmet());
	public static final RegistryObject<Item> COPPER_ARMOR_CHESTPLATE = REGISTRY.register("copper_armor_chestplate", () -> new CopperArmorItem.Chestplate());
	public static final RegistryObject<Item> COPPER_ARMOR_LEGGINGS = REGISTRY.register("copper_armor_leggings", () -> new CopperArmorItem.Leggings());
	public static final RegistryObject<Item> COPPER_ARMOR_BOOTS = REGISTRY.register("copper_armor_boots", () -> new CopperArmorItem.Boots());
	public static final RegistryObject<Item> MAGISCHES_FEEN_KATANA = REGISTRY.register("magisches_feen_katana", () -> new MagischesFeenKatanaItem());
	public static final RegistryObject<Item> BLOOD_BOTTLE = REGISTRY.register("blood_bottle", () -> new BloodBottleItem());
	public static final RegistryObject<Item> RIVERS_OF_BLOOD = REGISTRY.register("rivers_of_blood", () -> new RiversOfBloodItem());
	public static final RegistryObject<Item> RESET_MAX = REGISTRY.register("reset_max", () -> new ResetMaxItem());
	public static final RegistryObject<Item> RESET_1 = REGISTRY.register("reset_1", () -> new Reset1Item());
	public static final RegistryObject<Item> KURIKARAKEN = REGISTRY.register("kurikaraken", () -> new KurikarakenItem());
	public static final RegistryObject<Item> KURIKARAKEN_BLOCK = block(TheFourPrimitivesAndWeaponsModBlocks.KURIKARAKEN_BLOCK, TheFourPrimitivesAndWeaponsModTabs.TAB_YOPKEINAMONO);
	public static final RegistryObject<Item> PROTOTYPE_KATANA = REGISTRY.register("prototype_katana", () -> new PrototypeKatanaItem());
	public static final RegistryObject<Item> AAA = REGISTRY.register("aaa", () -> new AaaItem());
	public static final RegistryObject<Item> STORM = REGISTRY.register("storm_book", () -> new StormItem());
	public static final RegistryObject<Item> ONINOMEN_HELMET = REGISTRY.register("oninomen_helmet", () -> new OninomenItem.Helmet());
	public static final RegistryObject<Item> SMALL_SWORD = REGISTRY.register("small_sword", () -> new SmallSwordItem());
	public static final RegistryObject<Item> KATANA_NIGU_HUMERUS = REGISTRY.register("katana_nigu_humerus", () -> new KatanaNiguHumerusItem());
	public static final RegistryObject<Item> BOGGED_OUTER_HELMET = REGISTRY.register("bogged_outer_helmet", () -> new BoggedOuterItem.Helmet());
	public static final RegistryObject<Item> BOGGED_OUTER_CHESTPLATE = REGISTRY.register("bogged_outer_chestplate", () -> new BoggedOuterItem.Chestplate());
	public static final RegistryObject<Item> BOGGED_OUTER_LEGGINGS = REGISTRY.register("bogged_outer_leggings", () -> new BoggedOuterItem.Leggings());
	public static final RegistryObject<Item> BOGGED_OUTER_BOOTS = REGISTRY.register("bogged_outer_boots", () -> new BoggedOuterItem.Boots());
	public static final RegistryObject<Item> NIGU_SHIELD = REGISTRY.register("nigu_shield", () -> new NiguShieldItem());
	public static final RegistryObject<Item> DAS_HERZ_EINER_FEE_ARMOR_HELMET = REGISTRY.register("das_herz_einer_fee_armor_helmet", () -> new DasHerzEinerFeeArmorItem.Helmet());
	public static final RegistryObject<Item> DAS_HERZ_EINER_FEE_ARMOR_CHESTPLATE = REGISTRY.register("das_herz_einer_fee_armor_chestplate", () -> new DasHerzEinerFeeArmorItem.Chestplate());
	public static final RegistryObject<Item> DAS_HERZ_EINER_FEE_ARMOR_LEGGINGS = REGISTRY.register("das_herz_einer_fee_armor_leggings", () -> new DasHerzEinerFeeArmorItem.Leggings());
	public static final RegistryObject<Item> DAS_HERZ_EINER_FEE_ARMOR_BOOTS = REGISTRY.register("das_herz_einer_fee_armor_boots", () -> new DasHerzEinerFeeArmorItem.Boots());
	public static final RegistryObject<Item> STONE_KATANA_BLOCK = block(TheFourPrimitivesAndWeaponsModBlocks.STONE_KATANA_BLOCK, TheFourPrimitivesAndWeaponsModTabs.TAB_YOPKEINAMONO);
	public static final RegistryObject<Item> STONE_KATANA_BLOCK_1 = block(TheFourPrimitivesAndWeaponsModBlocks.STONE_KATANA_BLOCK_1, TheFourPrimitivesAndWeaponsModTabs.TAB_YOPKEINAMONO);
	public static final RegistryObject<Item> MACHETE = REGISTRY.register("machete", () -> new MacheteItem());
	public static final RegistryObject<Item> MAKIWARIDAI = block(TheFourPrimitivesAndWeaponsModBlocks.MAKIWARIDAI, TheFourPrimitivesAndWeaponsModTabs.TAB_YOPKEINAMONO);
	public static final RegistryObject<Item> DECORATION_POT_WITH_ARROWS = REGISTRY.register("decoration_pot_with_arrows", () -> new DecorationPotWithArrowsItem());
	public static final RegistryObject<Item> NINJATOU = REGISTRY.register("ninjatou", () -> new NinjatouItem());
	public static final RegistryObject<Item> GOLD_KATANA = REGISTRY.register("gold_katana", () -> new GoldKatanaItem());
	public static final RegistryObject<Item> KENTI = REGISTRY.register("kenti", () -> new KentiItem());
	public static final RegistryObject<Item> BLACKHOLE_SPAWN_EGG = REGISTRY.register("blackhole_spawn_egg",
			() -> new ForgeSpawnEggItem(TheFourPrimitivesAndWeaponsModEntities.BLACKHOLE, -16777216, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> DESPORN_KENTI = REGISTRY.register("desporn_kenti", () -> new DespornKentiItem());
	public static final RegistryObject<Item> DARKNESS = REGISTRY.register("darkness_book", () -> new DarknessItem());
	public static final RegistryObject<Item> DARKNESS_KATANA = REGISTRY.register("darkness_katana", () -> new DarknessKatanaItem());
	public static final RegistryObject<Item> FIREWORKS_BLACK = REGISTRY.register("fireworks_black", () -> new FireworksBlackItem());
	public static final RegistryObject<Item> SCYTHE = REGISTRY.register("scythe", () -> new ScytheItem());
	public static final RegistryObject<Item> WARDEN_ARMOR_HELMET = REGISTRY.register("warden_armor_helmet", () -> new WardenArmorItem.Helmet());
	public static final RegistryObject<Item> WARDEN_ARMOR_CHESTPLATE = REGISTRY.register("warden_armor_chestplate", () -> new WardenArmorItem.Chestplate());
	public static final RegistryObject<Item> WARDEN_ARMOR_LEGGINGS = REGISTRY.register("warden_armor_leggings", () -> new WardenArmorItem.Leggings());
	public static final RegistryObject<Item> CUSTOM_SMITHING_TABLE = block(TheFourPrimitivesAndWeaponsModBlocks.CUSTOM_SMITHING_TABLE, null);
	public static final RegistryObject<Item> KABUSERU = REGISTRY.register("kabuseru", () -> new KabuseruItem());
	public static final RegistryObject<Item> MOTASERU = REGISTRY.register("motaseru", () -> new MotaseruItem());
	public static final RegistryObject<Item> STONE_SLAB = REGISTRY.register("stone_slab", () -> new StoneSlabItem());
	public static final RegistryObject<Item> WITHER_KATANA = REGISTRY.register("wither_katana", () -> new WitherKatanaItem());
	public static final RegistryObject<Item> WITHER_SKELETON_SPAWNER = block(TheFourPrimitivesAndWeaponsModBlocks.WITHER_SKELETON_SPAWNER, TheFourPrimitivesAndWeaponsModTabs.TAB_YOPKEINAMONO);
	public static final RegistryObject<Item> SKIN_OF_DRAGON = REGISTRY.register("skin_of_dragon", () -> new SkinOfDragonItem());
	public static final RegistryObject<Item> CUSTOM_CRAFTER_CRAFTING = block(TheFourPrimitivesAndWeaponsModBlocks.CUSTOM_CRAFTER_CRAFTING, null);
	public static final RegistryObject<Item> QUESTBOOK = REGISTRY.register("questbook", () -> new QuestbookItem());
	public static final RegistryObject<Item> ARROW_HEAD = REGISTRY.register("arrow_head", () -> new ArrowHeadItem());
	public static final RegistryObject<Item> IMITATION = REGISTRY.register("imitation", () -> new ImitationItem());
	public static final RegistryObject<Item> STRAY_BONE = REGISTRY.register("stray_bone", () -> new StrayBoneItem());
	public static final RegistryObject<Item> WITHER_BONE = REGISTRY.register("wither_bone", () -> new WitherBoneItem());
	public static final RegistryObject<Item> METEOR_ARROW_SPAWN_EGG = REGISTRY.register("meteor_arrow_spawn_egg", () -> new ForgeSpawnEggItem(TheFourPrimitivesAndWeaponsModEntities.METEOR_ARROW, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> PUMPKIN_HEAD_HELMET = REGISTRY.register("pumpkin_head_helmet", () -> new PumpkinHeadItem.Helmet());
	public static final RegistryObject<Item> ZOMBIE_HEART = REGISTRY.register("zombie_heart", () -> new ZombieHeartItem.Helmet());
	public static final RegistryObject<Item> TUKAENA = REGISTRY.register("tukaena", () -> new TukaenaItem());
	public static final RegistryObject<Item> ITEM_STAN = block(TheFourPrimitivesAndWeaponsModBlocks.ITEM_STAN, TheFourPrimitivesAndWeaponsModTabs.TAB_MAGIC_BOOKS);
	public static final RegistryObject<Item> ALCHEMY_CRAFT_BLOCK = block(TheFourPrimitivesAndWeaponsModBlocks.ALCHEMY_CRAFT_BLOCK, null);
	public static final RegistryObject<Item> MAGICWAND = REGISTRY.register("magicwand", () -> new MagicwandItem());
	public static final RegistryObject<Item> OLD_KATANA = REGISTRY.register("old_katana", () -> new OldKatanaItem());
	public static final RegistryObject<Item> MAGIC_POT = block(TheFourPrimitivesAndWeaponsModBlocks.MAGIC_POT, TheFourPrimitivesAndWeaponsModTabs.TAB_MAGIC_BOOKS);
	public static final RegistryObject<Item> FLYING_ATTACKER_SPAWN_EGG = REGISTRY.register("flying_attacker_spawn_egg",
			() -> new ForgeSpawnEggItem(TheFourPrimitivesAndWeaponsModEntities.FLYING_ATTACKER, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> GATE = REGISTRY.register("gate", () -> new the_four_primitives_and_weapons.item.GateItem());
	public static final RegistryObject<Item> CONVERGENT_GATE = REGISTRY.register("convergent_gate", () -> new the_four_primitives_and_weapons.item.ConvergentGateItem());
	public static final RegistryObject<Item> IMMORTAL_CORE = REGISTRY.register("immortal_core", () -> new the_four_primitives_and_weapons.item.ImmortalCoreItem());
	public static final RegistryObject<Item> RARITY_CHARM = REGISTRY.register("rarity_charm", () -> new the_four_primitives_and_weapons.item.RarityCharmItem());
	public static final RegistryObject<Item> IRON_TYOKUTO = REGISTRY.register("iron_tyokuto", () -> new the_four_primitives_and_weapons.item.IronTyokutoItem());
	public static final RegistryObject<Item> IRON_DAGGER = REGISTRY.register("iron_dagger", () -> new the_four_primitives_and_weapons.item.IronDaggerItem());
	public static final RegistryObject<Item> WOODEN_DAGGER = REGISTRY.register("wooden_dagger", () -> new the_four_primitives_and_weapons.item.WoodenDaggerItem());
	public static final RegistryObject<Item> STONE_DAGGER = REGISTRY.register("stone_dagger", () -> new the_four_primitives_and_weapons.item.StoneDaggerItem());
	public static final RegistryObject<Item> GOLD_DAGGER = REGISTRY.register("gold_dagger", () -> new the_four_primitives_and_weapons.item.GoldDaggerItem());
	public static final RegistryObject<Item> DIAMOND_DAGGER = REGISTRY.register("diamond_dagger", () -> new the_four_primitives_and_weapons.item.DiamondDaggerItem());
	public static final RegistryObject<Item> NETHERITE_DAGGER = REGISTRY.register("netherite_dagger", () -> new the_four_primitives_and_weapons.item.NetheriteDaggerItem());
	public static final RegistryObject<Item> GOLD_TYOKUTO = REGISTRY.register("gold_tyokuto", () -> new the_four_primitives_and_weapons.item.GoldTyokutoItem());
	public static final RegistryObject<Item> STONE_TYOKUTO = REGISTRY.register("stone_tyokuto", () -> new the_four_primitives_and_weapons.item.StoneTyokutoItem());
	public static final RegistryObject<Item> SAYA = REGISTRY.register("saya", () -> new SayaItem());
    public static final RegistryObject<Item> NINJATO_RECALL_CHAIN = REGISTRY.register("ninjato_recall_chain",
        () -> new the_four_primitives_and_weapons.item.NinjatoRecallCordItem());
    public static final RegistryObject<Item> NINJATO_RECALL_CORD = REGISTRY.register("ninjato_recall_cord",
        () -> new the_four_primitives_and_weapons.item.NinjatoRecallCordItem());
	public static final RegistryObject<Item> NINJATO_SAYA = REGISTRY.register("ninjato_saya", () -> new SayaItem());
	public static final RegistryObject<Item> TYOKUTO_SAYA = REGISTRY.register("tyokuto_saya", () -> new TyokutoSayaItem());
	public static final RegistryObject<Item> SWORD_SAYA = REGISTRY.register("sword_saya", () -> new SwordSayaItem());
	public static final RegistryObject<Item> ICE_BOOK = REGISTRY.register("ice_book", () -> new IceBookItem());
	public static final RegistryObject<Item> ELECTRIC_BOOK = REGISTRY.register("electric_book", () -> new ElectricBookItem());
	public static final RegistryObject<Item> CORROSION_BOOK = REGISTRY.register("corrosion_book", () -> new CorrosionBookItem());
	public static final RegistryObject<Item> HOLY_BOOK = REGISTRY.register("holy_book", () -> new HolyBookItem());
	public static final RegistryObject<Item> ERASURE_BOOK = REGISTRY.register("erasure_book", () -> new ErasureBookItem());
	public static final RegistryObject<Item> MIASMA_BOOK = REGISTRY.register("miasma_book", () -> new MiasmaBookItem());
	public static final RegistryObject<Item> SOUL_BOOK = REGISTRY.register("soul_book", () -> new SoulBookItem());
	public static final RegistryObject<Item> SOUL_FIRE_BOOK = REGISTRY.register("soul_fire_book", () -> new SoulFireBookItem());
	public static final RegistryObject<Item> ELEMENT_CLEANSE_POTION = REGISTRY.register("element_cleanse_potion", () -> new ElementCleansePotionItem());
	public static final RegistryObject<Item> REITOU = REGISTRY.register("reitou", () -> new ReitouItem());
	public static final RegistryObject<Item> OFUDA = REGISTRY.register("ofuda", () -> new OfudaItem());
	public static final RegistryObject<Item> WOODEN_RAPIER = REGISTRY.register("wooden_rapier", () -> new WoodenRapierItem());
	public static final RegistryObject<Item> STONE_RAPIER = REGISTRY.register("stone_rapier", () -> new StoneRapierItem());
	public static final RegistryObject<Item> IRON_RAPIER = REGISTRY.register("iron_rapier", () -> new IronRapierItem());
	public static final RegistryObject<Item> GOLD_RAPIER = REGISTRY.register("gold_rapier", () -> new GoldRapierItem());
	public static final RegistryObject<Item> DIAMOND_RAPIER = REGISTRY.register("diamond_rapier", () -> new DiamondRapierItem());
	public static final RegistryObject<Item> NETHERITE_RAPIER = REGISTRY.register("netherite_rapier", () -> new NetheriteRapierItem());
	public static final RegistryObject<Item> RAPIER_SAYA = REGISTRY.register("rapier_saya", () -> new RapierSayaItem());
	public static final RegistryObject<Item> DAGGER_SAYA = REGISTRY.register("dagger_saya", () -> new the_four_primitives_and_weapons.item.DaggerSayaItem());
	public static final RegistryObject<Item> PARRY_SHIELD = REGISTRY.register("parry_shield", () -> new ParryShieldItem());

	// 漆 ( 原木から採れる生漆 → 漆黒/朱の漆。 鞘に塗って塗鞘スタイルにする )
	public static final RegistryObject<Item> RAW_URUSHI = REGISTRY.register("raw_urushi", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> URUSHI_BLACK = REGISTRY.register("urushi_black", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> URUSHI_RED = REGISTRY.register("urushi_red", () -> new Item(new Item.Properties()));

	private static RegistryObject<Item> block(RegistryObject<Block> block, Object tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
