(require :asdf)
(defpackage :mcfunction-lisp
  (:use :cl)
  (:export :make-project :*project* :command :emit-function :function-call
           :on-load :on-tick :write-project :write-function-file))
(in-package :mcfunction-lisp)
(defstruct (project (:constructor %make-project)) namespace format directory description
  (functions (make-hash-table :test 'equal)) (load-hooks nil) (tick-hooks nil))
(defvar *project* nil)
(defun valid-name-p (name &optional path)
  (and (stringp name) (plusp (length name))
       (every (lambda (c) (or (find c "abcdefghijklmnopqrstuvwxyz0123456789_.-")
                              (and path (char= c #\/)))) name)
       (not (find name '("." "..") :test #'equal))
       (or (not path) (every (lambda (part) (and (plusp (length part))
                              (not (member part '("." "..") :test #'equal))))
                            (uiop:split-string name :separator "/")))))
(defun make-project (&key (namespace "example") (pack-format 15) (function-directory "functions")
                          (description "Generated with Common Lisp"))
  (unless (and (valid-name-p namespace) (integerp pack-format) (plusp pack-format)
               (member function-directory '("functions" "function") :test #'equal) (stringp description))
    (error "Invalid namespace, pack format, function directory or description."))
  (%make-project :namespace namespace :format pack-format :directory function-directory :description description))
(defun command (control &rest args)
  "Format one Minecraft command; no leading slash or embedded line breaks."
  (let ((line (apply #'format nil control args)))
    (when (or (find #\Newline line) (find #\Return line) (find #\Null line)
              (and (plusp (length line)) (char= (char line 0) #\/)))
      (error "Expected a single mcfunction line without a leading slash: ~S" line))
    line))
(defun checked-lines (lines)
  (mapcar (lambda (line) (unless (stringp line) (error "Command is not a string: ~S" line))
                      (command "~A" line)) (coerce lines 'list)))
(defun emit-function (name lines &optional (project *project*))
  (unless (and project (valid-name-p name t)) (error "Invalid function path: ~S" name))
  (when (nth-value 1 (gethash name (project-functions project))) (error "Duplicate function: ~A" name))
  (setf (gethash name (project-functions project)) (checked-lines lines))
  name)
(defun reference (name project)
  (let ((parts (uiop:split-string name :separator ":")))
    (cond ((and (= (length parts) 1) (valid-name-p name t))
           (format nil "~A:~A" (project-namespace project) name))
          ((and (= (length parts) 2) (valid-name-p (first parts)) (valid-name-p (second parts) t)) name)
          (t (error "Invalid function reference: ~S" name)))))
(defun function-call (name &optional (project *project*)) (format nil "function ~A" (reference name project)))
(defun on-load (name &optional (project *project*)) (pushnew (reference name project) (project-load-hooks project) :test #'equal))
(defun on-tick (name &optional (project *project*)) (pushnew (reference name project) (project-tick-hooks project) :test #'equal))
(defun json-string (string)
  (with-output-to-string (out)
    (write-char #\" out)
    (loop for c across string do
      (case c (#\" (write-string "\\\"" out)) (#\\ (write-string "\\\\" out))
        (otherwise (if (< (char-code c) 32) (format out "\\u~4,'0X" (char-code c)) (write-char c out)))))
    (write-char #\" out)))
(defun write-text-file (file text &key (if-exists :error))
  (ensure-directories-exist file)
  (with-open-file (out file :direction :output :if-exists if-exists :external-format :utf-8)
    (write-string text out)))
(defun write-function-file (root namespace name lines &key (function-directory "functions") (if-exists :error))
  "Write one function into an existing pack. Explicit :SUPERSEDE allows replacing a generated file."
  (make-project :namespace namespace :function-directory function-directory)
  (unless (valid-name-p name t) (error "Invalid function path: ~S" name))
  (let ((text (format nil "~{~A~%~}" (checked-lines lines))))
    (write-text-file (merge-pathnames (format nil "data/~A/~A/~A.mcfunction" namespace function-directory name)
                                     (uiop:ensure-directory-pathname root)) text :if-exists if-exists)))
(defun write-project (project output)
  "Export a new datapack directory. Existing directories are never overwritten."
  (let ((root (uiop:ensure-directory-pathname (merge-pathnames output (uiop:getcwd)))))
    (when (probe-file root) (error "Output already exists: ~A" root))
    ;; Check local hooks before creating any files. External namespace hooks are allowed.
    (dolist (hook (append (project-load-hooks project) (project-tick-hooks project)))
      (let ((parts (uiop:split-string hook :separator ":")))
        (when (and (equal (first parts) (project-namespace project))
                   (not (nth-value 1 (gethash (second parts) (project-functions project)))))
          (error "Hook refers to missing function: ~A" hook))))
    (write-text-file (merge-pathnames "pack.mcmeta" root)
      (format nil "{\"pack\":{\"pack_format\":~D,\"description\":~A}}~%" (project-format project) (json-string (project-description project))))
    (maphash (lambda (name lines) (write-function-file root (project-namespace project) name lines
                                  :function-directory (project-directory project))) (project-functions project))
    (loop for name in '("load" "tick") for hooks in (list (project-load-hooks project) (project-tick-hooks project))
      when hooks do (write-text-file (merge-pathnames (format nil "data/minecraft/tags/~A/~A.json" (project-directory project) name) root)
        (format nil "{\"values\":[~{~A~^,~}]}~%" (mapcar #'json-string (reverse hooks)))))
    root))
