(load (merge-pathnames "library.lisp" *load-truename*))
(in-package :mcfunction-lisp)
(defun must-fail (fn) (assert (handler-case (progn (funcall fn) nil) (error () t))))
(let* ((root (uiop:ensure-directory-pathname (first (uiop:command-line-arguments))))
       (*project* (make-project :namespace "portable" :description "日本語\"テスト")))
  (emit-function "empty" nil)
  (must-fail (lambda () (emit-function "empty" '("say duplicate"))))
  (dolist (name '("../escape" "/absolute" "a/../../b" "a//b" "BadName"))
    (must-fail (lambda () (emit-function name '("say bad")))))
  (must-fail (lambda () (command "say hello~%kill @e")))
  (must-fail (lambda () (command "/say hello")))
  (emit-function "hello" (list "say vanilla only" (function-call "empty")))
  (on-load "hello")
  (write-project *project* (merge-pathnames "plural/" root))
  (must-fail (lambda () (write-project *project* (merge-pathnames "plural/" root))))
  (let ((*project* (make-project :namespace "portable" :function-directory "function" :pack-format 48)))
    (emit-function "hello" '("say singular")) (on-tick "hello")
    (write-project *project* (merge-pathnames "singular/" root)))
  (let ((*project* (make-project)))
    (on-load "missing")
    (must-fail (lambda () (write-project *project* (merge-pathnames "invalid/" root))))
    (assert (not (probe-file (merge-pathnames "invalid/" root))))))
(format t "Portable bridge: paths, duplicate/empty functions, hooks, layouts and overwrite protection passed.~%")
