(load "lisp/assets/generate.lisp")
(load "lisp/maintenance/codemod-level.lisp")
(load "lisp/generate/photo-world.lisp")
(in-package :maw-tools)
(let* ((ref (make-array 8 :element-type '(unsigned-byte 8) :initial-contents '(100 100 100 255 200 200 200 0)))
       (out (recolor-pixels ref '(200 80 40))))
  (assert (equalp out #(200 80 40 255 0 0 0 0)))
  (assert (equal (dominant-color ref) '(100 100 100))))
(let ((path (format nil "/tmp/maw-codec-~D.png" (get-universal-time)))
      (pixels (make-array 8 :element-type '(unsigned-byte 8) :initial-contents '(10 20 30 255 50 60 70 12))))
  (unwind-protect
      (progn (image-save path pixels 2 1)
             (multiple-value-bind (actual w h) (image-load path)
               (assert (= w 2)) (assert (= h 1)) (assert (equalp actual pixels))))
    (when (probe-file path) (delete-file path))))
(assert (equal (migrate-level "foo.level; foo.level(); foo.levelName; \"foo.level\"; /* foo.level */")
               "foo.level(); foo.level(); foo.levelName; \"foo.level\"; /* foo.level */"))
(assert (equal (migrate-level "foo.level ()") "foo.level ()"))
(assert (equal (migrate-level "import foo.level;") "import foo.level;"))
(format t "Lisp migration tests: pixel masks, RGB, PNG roundtrip, codemod passed.~%")
