(load "lisp/generate/commands.lisp")
(load "lisp/maintenance/lock-codes.lisp")
(in-package :maw-tools)
(assert (= 49 (length (variant-names))))
(assert (equal "dreamwing" (car (last (variant-names)))))
(assert (equal (encode (object "flag" :true "name" "刀\"")) "{flag:1b,name:\"刀\\\"\"}"))
(let* ((source "{\"text\":\"刀\\n\\uD83E\\uDD8B\",\"v\":[true,false,null,12,-3.5]}")
       (parsed (parse-json source)) (again (parse-json (encode parsed t))))
  (assert (equal (gethash "text" parsed) (gethash "text" again)))
  (assert (eq :false (aref (gethash "v" again) 1))))
(assert (not (coordinate-valid-p "~;kill")))
(assert (not (coordinate-valid-p "#.(quit)")))
(assert (coordinate-valid-p "~-1.5"))
(assert (not (coordinate-valid-p "~~1")))
(let ((*standard-input* (make-string-input-stream (format nil "1~%2~%2~%刀~%1~%~~ ~~1.5 ~~~%90~%85~%0~%1.5~%")))
      (*standard-output* (make-broadcast-stream)))
  (let ((command (weapon-command)))
    (assert (search "stabbed_weapon ~ ~1.5 ~" command))
    (assert (search "DisappearOnPickup:1b" command))
    (assert (search "StabScale:1.5f" command))))
(let* ((path (format nil "/tmp/maw-lock-test-~D.json" (get-universal-time)))
       (source "{\"mod_elements\":[{\"locked_code\":false},{\"locked_code\":true},{\"name\":\"新規\"}],\"other\":17}"))
  (unwind-protect
      (progn (write-text path source) (lock-workspace path)
             (let ((d (parse-json (read-text path))))
               (assert (= 17 (gethash "other" d)))
               (assert (eq :true (gethash "locked_code" (aref (gethash "mod_elements" d) 0))))
               (assert (not (gethash "locked_code" (aref (gethash "mod_elements" d) 2)))))
             (assert (equal source (read-text (concatenate 'string path ".backup_auto"))))
    (delete-file path) (delete-file (concatenate 'string path ".backup_auto")))))
(format t "Lisp command/JSON/NBT/lock tests passed.~%")
