;;; Compare release JAR resources, class interfaces and source lines. SBCL + unzip.
(require :asdf)
(defpackage :compact-jar-check (:use :cl))
(in-package :compact-jar-check)
(defvar *bytes*)
(defvar *offset*)
(defun uint (count)
  (let ((value 0))
    (dotimes (i count value)
      (setf value (+ (ash value 8) (aref *bytes* *offset*))) (incf *offset*))))
(defun take-bytes (count)
  (prog1 (subseq *bytes* *offset* (+ *offset* count)) (incf *offset* count)))
(defun binary-file (path)
  (with-open-file (in path :element-type '(unsigned-byte 8))
    (let ((bytes (make-array (file-length in) :element-type '(unsigned-byte 8))))
      (read-sequence bytes in) bytes)))
(defun attributes (pool)
  (loop repeat (uint 2) collect (let ((name (aref pool (uint 2)))) (cons name (take-bytes (uint 4))))))
(defun describe-class (bytes)
  (let ((*bytes* bytes) (*offset* 0))
    (assert (= (uint 4) #xcafebabe))
    (let* ((version (list (uint 2) (uint 2))) (pool (make-array (uint 2) :initial-element nil)))
      (loop for i from 1 below (length pool) for tag = (uint 1) do
        (case tag
          (1 (setf (aref pool i) (map 'string #'code-char (take-bytes (uint 2)))))
          ((3 4) (take-bytes 4)) ((5 6) (take-bytes 8) (incf i))
          ((7 8 16 19 20) (setf (aref pool i) (uint 2)))
          ((9 10 11 12 17 18) (take-bytes 4)) (15 (take-bytes 3))
          (otherwise (error "Unknown constant pool tag ~A" tag))))
      (labels ((pool-class-name (index) (unless (zerop index) (aref pool (aref pool index)))))
        (let* ((access (uint 2)) (name (pool-class-name (uint 2))) (parent (pool-class-name (uint 2)))
               (interfaces (loop repeat (uint 2) collect (pool-class-name (uint 2))))
               (members nil) (lines nil) (locals 0))
          (dotimes (group 2)
            (loop repeat (uint 2) do
              (let ((flags (uint 2)) (member (aref pool (uint 2))) (descriptor (aref pool (uint 2))))
                (push (list group flags member descriptor) members)
                (dolist (attr (attributes pool))
                  (when (equal (car attr) "Code")
                    (let ((*bytes* (cdr attr)) (*offset* 0) (method-lines nil))
                      (uint 2) (uint 2) (take-bytes (uint 4)) (take-bytes (* 8 (uint 2)))
                      (dolist (nested (attributes pool))
                        (let ((*bytes* (cdr nested)) (*offset* 0))
                          (cond
                            ((equal (car nested) "LocalVariableTable") (incf locals (uint 2)))
                            ((equal (car nested) "LineNumberTable")
                             (setf method-lines (loop repeat (uint 2) collect (progn (uint 2) (uint 2))))))))
                      (push (list member descriptor method-lines) lines)))))))
          (let ((sources (loop for attr in (attributes pool) when (equal (car attr) "SourceFile")
                               collect (let ((*bytes* (cdr attr)) (*offset* 0)) (aref pool (uint 2))))))
            (values (list version access name parent interfaces (nreverse members) (nreverse lines) sources) locals)))))))
(defun command (&rest args) (uiop:run-program args :output :string :error-output *error-output*))
(defun entries (archive)
  (remove "" (uiop:split-string (command "unzip" "-Z1" archive) :separator '(#\Newline)) :test #'equal))
(let ((args (uiop:command-line-arguments)))
  (unless (= (length args) 2) (error "Usage: sbcl --script lisp/test/verify-compact-jar.lisp BEFORE.jar AFTER.jar"))
  (let* ((before (namestring (truename (first args)))) (after (namestring (truename (second args))))
         (names (entries before))
         (temporary (uiop:ensure-directory-pathname (string-trim '(#\Newline) (command "mktemp" "-d"))))
         (left (merge-pathnames "before/" temporary)) (right (merge-pathnames "after/" temporary)))
    (unwind-protect
         (progn
           (assert (equal names (entries after)))
           (assert (= (length names) (length (remove-duplicates names :test #'equal))))
           (dolist (name names)
             (when (or (uiop:absolute-pathname-p name) (find ".." (uiop:split-string name :separator "/") :test #'equal))
               (error "Unsafe archive path: ~A" name)))
           (command "unzip" "-tq" before) (command "unzip" "-tq" after)
           (command "unzip" "-qq" before "-d" (namestring left))
           (command "unzip" "-qq" after "-d" (namestring right))
           (let ((classes 0) (resources 0) (removed 0))
             (dolist (name names)
               (if (char= (char name (1- (length name))) #\/)
                   (incf resources)
                   (let ((old (binary-file (merge-pathnames name left))) (new (binary-file (merge-pathnames name right))))
                     (if (equal (pathname-type name) "class")
                         (multiple-value-bind (a old-count) (describe-class old)
                           (multiple-value-bind (b new-count) (describe-class new)
                             (assert (equalp a b) () "Class interface or source lines changed: ~A" name)
                             (assert (zerop new-count)) (incf classes) (incf removed old-count)))
                         (progn (assert (equalp old new) () "Resource changed: ~A" name) (incf resources))))))
             (format t "~D classes/source lines preserved; ~D resources unchanged; ~D local-variable records removed; ZIP CRCs valid.~%" classes resources removed)))
      (uiop:delete-directory-tree temporary :validate t :if-does-not-exist :ignore))))
