(load "lisp/assets/images.lisp")
(in-package :maw-tools)
(defparameter *flowering-woods*
  '(("kinmokusei" "金木犀" "Fragrant Orange Osmanthus" #x315A32 #xF8A128 #x8B7450)
    ("ginmokusei" "銀木犀" "Fragrant White Osmanthus" #x3F6542 #xFFF4D6 #xA08A64)
    ("shidare_ume" "枝垂れ梅" "Weeping Japanese Apricot" #x667548 #xF1ADC4 #x6F534B)
    ("tsubaki" "椿" "Camellia" #x254C39 #xCB344B #x96705D)))
(defun wood-json (path value) (write-text (concatenate 'string "src/main/resources/" path) (encode value t)))
(defun wood-tag (category name values)
  (let* ((path (format nil "src/main/resources/data/minecraft/tags/~A/~A.json" category name))
         (tag (if (probe-file path) (parse-json (read-text path)) (object "replace" :false "values" #()))))
    (setf (gethash "values" tag) (coerce (remove-duplicates (append (coerce (gethash "values" tag) 'list) values) :test #'equal) 'vector))
    (write-text path (encode tag t))))
(defvar *wood-reference-directory*)
(defparameter *wood-reference-files*
  '(("log" . "oak_log") ("top" . "oak_log_top") ("stripped" . "stripped_oak_log")
    ("planks" . "oak_planks") ("leaves" . "azalea_leaves")
    ("flowers" . "flowering_azalea_leaves") ("sapling" . "oak_sapling")))
(defun wood-pixel-group (source index mode)
  (let ((r (aref source index)) (g (aref source (+ index 1))) (b (aref source (+ index 2))))
    (cond ((and (equal mode "flowers") (> r (+ g 8)) (> b (* g 0.7))) :flower)
          ((or (member mode '("leaves" "flowers") :test #'equal)
               (and (equal mode "sapling") (> g r))) :leaf)
          (t :bark))))
(defun wood-recolor (source mode green flower bark)
  (let ((out (copy-seq source)) (sums (make-hash-table)) (counts (make-hash-table)))
    (loop for i from 0 below (length source) by 4 when (> (aref source (+ i 3)) 0) do
      (let ((group (wood-pixel-group source i mode)))
        (incf (gethash group sums 0d0) (luminance source i)) (incf (gethash group counts 0))))
    (loop for i from 0 below (length source) by 4 when (> (aref source (+ i 3)) 0) do
      (let* ((group (wood-pixel-group source i mode))
             (target (case group (:leaf green) (:flower flower) (t bark)))
             (shade (/ (luminance source i) (max 1d0 (/ (gethash group sums) (gethash group counts))))))
        (loop for shift in '(16 8 0) for c from 0 do
          (setf (aref out (+ i c)) (min 255 (max 0 (round (* shade (ldb (byte 8 shift) target)))))))))
    out))
(defun wood-texture (name mode green flower bark)
  (let ((reference (cdr (assoc mode *wood-reference-files* :test #'equal))))
    (multiple-value-bind (source width height)
        (image-load (namestring (merge-pathnames (format nil "~A.png" reference) *wood-reference-directory*)))
      (image-save (format nil "src/main/resources/assets/the_four_primitives_and_weapons/textures/block/flowering_woods/~A_~A.png" name mode)
                  (wood-recolor source mode green flower bark) width height))))
(defun flowering-wood-assets ()
  (let ((logs nil) (leaves nil) (planks nil) (saplings nil))
    (dolist (wood *flowering-woods*)
      (destructuring-bind (name ja en green flower bark) wood
        (dolist (mode '("log" "top" "stripped" "planks" "leaves" "flowers" "sapling")) (wood-texture name mode green flower bark))
        (let ((ids (list (format nil "~A_log" name) (format nil "stripped_~A_log" name) (format nil "~A_planks" name)
                         (format nil "~A_leaves" name) (format nil "flowering_~A_leaves" name) (format nil "~A_sapling" name))))
          (loop for id in ids for kind in '("log" "stripped" "planks" "leaves" "flowers" "sapling") do
            (let* ((ref (format nil "the_four_primitives_and_weapons:~A" id))
                   (texture (format nil "the_four_primitives_and_weapons:block/flowering_woods/~A_~A" name kind))
                   (model (format nil "the_four_primitives_and_weapons:block/~A" id))
                   (islog (member kind '("log" "stripped") :test #'equal))
                   (isleaf (member kind '("leaves" "flowers") :test #'equal)))
              (wood-json (format nil "assets/the_four_primitives_and_weapons/blockstates/~A.json" id)
                (object "variants" (if islog (object "axis=y" (object "model" model)
                     "axis=x" (object "model" model "x" 90 "y" 90) "axis=z" (object "model" model "x" 90)) (object "" (object "model" model)))))
              (wood-json (format nil "assets/the_four_primitives_and_weapons/models/block/~A.json" id)
                (cond (islog (object "parent" "minecraft:block/cube_column" "textures" (object "side" texture "end" (format nil "the_four_primitives_and_weapons:block/flowering_woods/~A_top" name))))
                  ((equal kind "sapling") (object "parent" "minecraft:block/cross" "render_type" "minecraft:cutout" "textures" (object "cross" texture)))
                  (t (object "parent" (if isleaf "minecraft:block/leaves" "minecraft:block/cube_all") "render_type" (if isleaf "minecraft:cutout" "minecraft:solid") "textures" (object "all" texture)))))
              (wood-json (format nil "assets/the_four_primitives_and_weapons/models/item/~A.json" id)
                (if (equal kind "sapling") (object "parent" "minecraft:item/generated" "textures" (object "layer0" texture)) (object "parent" model)))
              (wood-json (format nil "data/the_four_primitives_and_weapons/loot_tables/blocks/~A.json" id)
                (if isleaf
                  (parse-json (with-output-to-string (out)
                    (let ((text (read-text "src/main/resources/data/the_four_primitives_and_weapons/loot_tables/blocks/urushi_leaves.json")))
                      (loop for start = 0 then (+ end (length "urushi_leaves")) for end = (search "urushi_leaves" text :start2 start)
                        do (write-string text out :start start :end end) when end do (write-string id out) while end))))
                  (object "type" "minecraft:block" "pools" (vector (object "rolls" 1 "entries" (vector (object "type" "minecraft:item" "name" ref)) "conditions" (vector (object "condition" "minecraft:survives_explosion")))))))
              ;; Correct the inherited sapling reference in the leaf loot template.
              (when isleaf
                (let* ((file (format nil "src/main/resources/data/the_four_primitives_and_weapons/loot_tables/blocks/~A.json" id)) (text (read-text file)) (pos (search "urushi_sapling" text)))
                  (when pos (write-text file (concatenate 'string (subseq text 0 pos) name "_sapling" (subseq text (+ pos 14)))))))
              (cond (islog (push ref logs)) (isleaf (push ref leaves)) ((equal kind "planks") (push ref planks)) (t (push ref saplings)))))
          (loop for lang in '("ja_jp" "en_us") for label in (list ja en) do
            (let* ((file (format nil "src/main/resources/assets/the_four_primitives_and_weapons/lang/~A.json" lang)) (data (parse-json (read-text file))))
              (loop for id in ids for suffix in (if (equal lang "ja_jp") '("の原木" "の樹皮を剥いだ原木" "の板材" "の葉" "の花付きの葉" "の苗木") '(" Log" " Stripped Log" " Planks" " Leaves" " Flowering Leaves" " Sapling")) do
                (setf (gethash (format nil "block.the_four_primitives_and_weapons.~A" id) data) (concatenate 'string label suffix)))
              (write-text file (encode data t))))
          (wood-json (format nil "data/the_four_primitives_and_weapons/worldgen/configured_feature/~A_tree.json" name)
            (object "type" (format nil "the_four_primitives_and_weapons:~A_tree" name) "config" (object)))
          (wood-json (format nil "data/the_four_primitives_and_weapons/recipes/~A_planks.json" name)
            (object "type" "minecraft:crafting_shapeless" "ingredients" (vector (vector (object "item" (format nil "the_four_primitives_and_weapons:~A_log" name)) (object "item" (format nil "the_four_primitives_and_weapons:stripped_~A_log" name))))
              "result" (object "item" (format nil "the_four_primitives_and_weapons:~A_planks" name) "count" 4))))))
    (dolist (category '("blocks" "items"))
      (wood-tag category "logs" logs) (wood-tag category "logs_that_burn" logs)
      (wood-tag category "leaves" leaves) (wood-tag category "planks" planks) (wood-tag category "saplings" saplings))
    (wood-tag "blocks" "mineable/axe" (append logs planks))))
(defun flowering-wood-main ()
  (let* ((args (uiop:command-line-arguments))
         (jar (cond ((null args) (merge-pathnames ".gradle/caches/forge_gradle/minecraft_repo/versions/1.20.1/client.jar" (user-homedir-pathname)))
                    ((and (= (length args) 2) (equal (first args) "--vanilla-jar")) (pathname (second args)))
                    (t (error "--vanilla-jar Minecraft 1.20.1 client.jar"))))
         (*wood-reference-directory* (merge-pathnames (format nil "maw-wood-reference-~D-~D/" (get-universal-time) (random 1000000000 (make-random-state t))) (uiop:temporary-directory))))
    (unless (probe-file jar) (error "バニラ1.20.1のclient.jarを--vanilla-jarで指定してください"))
    (when (probe-file *wood-reference-directory*) (error "一時保存先が既存です"))
    (unwind-protect
      (progn
        (ensure-directories-exist (merge-pathnames "placeholder" *wood-reference-directory*))
        (uiop:run-program (append (list "unzip" "-q" "-j" (namestring jar))
          (mapcar (lambda (entry) (format nil "assets/minecraft/textures/block/~A.png" (cdr entry))) *wood-reference-files*)
          (list "-d" (namestring *wood-reference-directory*))))
        (flowering-wood-assets))
      (uiop:delete-directory-tree *wood-reference-directory* :validate t :if-does-not-exist :ignore))))
(unless (member "--test" (uiop:command-line-arguments) :test #'equal) (flowering-wood-main))
