(load "lisp/assets/images.lisp")
(in-package :maw-tools)
(defparameter *textures* "src/main/resources/assets/the_four_primitives_and_weapons/textures/")
(defun options (args)
  (let ((opts (object)) (pos nil))
    (loop while args for arg = (pop args) do
      (if (uiop:string-prefix-p "--" arg)
          (progn (unless args (error "~Aの値が必要" arg)) (setf (gethash arg opts) (pop args))) (push arg pos)))
    (values opts (nreverse pos))))
(defun fitting-main (args)
  (multiple-value-bind (opts pos) (options args)
    (unless (= (length pos) 3) (error "fit 素材画像 部位 出力名 [--weapon katana|tyokuto|rapier] [--color RRGGBB] [--mode recolor|sample] [--output PNG]"))
    (destructuring-bind (input part name) pos
      (let* ((rapier (member part '("grip" "guard" "pommel") :test #'equal))
             (weapon (gethash "--weapon" opts (if rapier "rapier" "katana")))
             (index (position part (if (equal weapon "rapier") '("grip" "guard" "pommel") '("tuka" "tuba" "kasira")) :test #'equal))
             (folder (cond ((equal weapon "katana") "katana_fitting/") ((equal weapon "tyokuto") "straight_katana_fitting/")
                           ((equal weapon "rapier") "rapier_fitting/") (t (error "武器種が不正"))))
             (sub (and index (nth index (if (equal weapon "rapier") '("grip/" "guard/" "pommel/") '("tsuka/" "tsuba/" "kasira/")))))
             (mode (gethash "--mode" opts "recolor")))
        (unless sub (error "部位が不正です"))
        (unless (and (> (length name) 0) (every (lambda (c) (or (alphanumericp c) (find c "_-"))) name)) (error "出力名にパスは指定できません"))
        (unless (member mode '("recolor" "sample") :test #'equal) (error "modeが不正"))
        (multiple-value-bind (ref w h) (image-load (concatenate 'string *textures* folder sub (if (equal weapon "katana") "iron_" "") part ".png"))
          (let* ((hex (gethash "--color" opts))
                 (out (if (equal mode "sample")
                          (multiple-value-bind (src sw sh) (image-load input) (sample-pixels ref w h src sw sh))
                          (recolor-pixels ref
                            (if hex (let ((text (string-left-trim "#" hex)))
                                      (unless (and (= (length text) 6) (every (lambda (c) (digit-char-p c 16)) text)) (error "RGBが不正"))
                                      (loop for i from 0 below 6 by 2 collect (parse-integer text :start i :end (+ i 2) :radix 16)))
                                (dominant-color (image-load input))))))
                 (path (gethash "--output" opts (concatenate 'string *textures* folder sub name ".png"))))
            (image-save path out w h) (format t "生成: ~A (~Dx~D)~%" path w h)))))))
(defun noise-main (args)
  (multiple-value-bind (opts pos) (options args)
    (when pos (error "noiseは --output PNG / --font TTF を指定できます"))
    (multiple-value-bind (data w h) (image-load (gethash "--font" opts "default") "glyphs")
      (let ((seed 42))
        (labels ((rnd (n) (setf seed (mod (+ (* seed 1664525) 1013904223) 4294967296)) (mod seed n)))
          (dotimes (cell 96)
            (let* ((x (* (mod cell 16) 16)) (y (* (floor cell 16) 16))
                   (x0 (max 0 (- x 2))) (y0 (max 0 (- y 2))) (x1 (min w (+ x 18))) (y1 (min h (+ y 18))))
              (dotimes (dot (floor (* (- x1 x0) (- y1 y0) .04d0)))
                (declare (ignorable dot))
                (let* ((i (* 4 (+ x0 (rnd (- x1 x0)) (* w (+ y0 (rnd (- y1 y0)))))))
                       (bright (+ 140 (rnd 116))))
                  (dotimes (c 3) (setf (aref data (+ i c)) bright)) (setf (aref data (+ i 3)) (+ 100 (rnd 101)))))))
          (dotimes (y h)
            (when (< (rnd 100) 8)
              (let ((row (subseq data (* y w 4) (* (1+ y) w 4))) (shift (- (rnd 5) 2)))
                (dotimes (x w) (dotimes (c 4)
                  (setf (aref data (+ (* 4 (+ x (* y w))) c))
                        (if (<= 0 (- x shift) (1- w)) (aref row (+ (* 4 (- x shift)) c)) 0))))))
            (when (oddp y) (dotimes (x w) (dotimes (c 3)
              (let ((i (+ (* 4 (+ x (* y w))) c))) (setf (aref data i) (floor (* .8d0 (aref data i)))))))))))
      (let ((path (gethash "--output" opts (concatenate 'string *textures* "font/static_noise.png"))))
        (image-save path data w h) (format t "生成: ~A (~Dx~D)~%" path w h)))))
(defun asset-main ()
  (let* ((args (uiop:command-line-arguments)) (mode (pop args)))
    (cond ((equal mode "fit") (fitting-main args)) ((equal mode "noise") (noise-main args)) (t (error "fit または noise を指定")))))
(unless (member "--test" (uiop:command-line-arguments) :test #'equal) (run-tool #'asset-main))
