(load "lisp/common/core.lisp")
(in-package :maw-tools)
(defun temp-path () (format nil "/tmp/maw-image-~D-~D.raw" (get-universal-time) (random 1000000000 (make-random-state t))))
(defun u32-read (stream) (loop repeat 4 for value = (read-byte stream) then (+ (* value 256) (read-byte stream)) finally (return value)))
(defun uint-write (value count stream) (loop for shift downfrom (* 8 (1- count)) to 0 by 8 do (write-byte (ldb (byte 8 shift) value) stream)))
(defun read-raw (path)
  (with-open-file (in path :element-type '(unsigned-byte 8))
    (let* ((w (u32-read in)) (h (u32-read in)) (data (make-array (* w h 4) :element-type '(unsigned-byte 8))))
      (assert (= (length data) (read-sequence data in))) (values data w h))))
(defun write-raw (path pixels w h)
  (with-open-file (out path :direction :output :if-exists :supersede :element-type '(unsigned-byte 8))
    (uint-write w 4 out) (uint-write h 4 out) (write-sequence pixels out)))
(defun image-load (path &optional (mode "decode"))
  (let ((temp (temp-path)))
    (unwind-protect
        (progn (uiop:run-program (list "java" "-Djava.awt.headless=true" "lisp/common/ImageBridge.java" mode path temp) :output *error-output*)
               (read-raw temp))
      (when (probe-file temp) (delete-file temp)))))
(defun image-save (path pixels w h)
  (ensure-directories-exist path)
  (let ((temp (temp-path)))
    (unwind-protect
        (progn (write-raw temp pixels w h)
               (uiop:run-program (list "java" "-Djava.awt.headless=true" "lisp/common/ImageBridge.java" "encode" temp path) :output *error-output*))
      (when (probe-file temp) (delete-file temp)))))
(defun luminance (data i) (+ (* .3d0 (aref data i)) (* .59d0 (aref data (+ i 1))) (* .11d0 (aref data (+ i 2)))))
(defun dominant-color (data)
  (let ((r 0) (g 0) (b 0) (n 0))
    (loop for i from 0 below (length data) by 4 when (and (>= (aref data (+ i 3)) 10) (<= 25 (luminance data i) 245))
          do (incf r (aref data i)) (incf g (aref data (+ i 1))) (incf b (aref data (+ i 2))) (incf n))
    (if (zerop n) '(150 150 150) (list (floor r n) (floor g n) (floor b n)))))
(defun recolor-pixels (reference color)
  (let ((sum 0d0) (n 0) (out (make-array (length reference) :element-type '(unsigned-byte 8) :initial-element 0)))
    (loop for i from 0 below (length reference) by 4 when (>= (aref reference (+ i 3)) 10) do (incf sum (luminance reference i)) (incf n))
    (let ((mean (max 1d0 (/ sum (max 1 n)))))
      (loop for i from 0 below (length reference) by 4 when (>= (aref reference (+ i 3)) 10) do
        (loop for c in color for channel from 0 do (setf (aref out (+ i channel)) (min 255 (floor (* c (/ (luminance reference i) mean))))))
        (setf (aref out (+ i 3)) 255))) out))
(defun sample-pixels (ref w h src sw sh)
  (let ((out (make-array (length ref) :element-type '(unsigned-byte 8) :initial-element 0)))
    (loop for y below h do (loop for x below w for i = (* 4 (+ x (* y w)))
      when (>= (aref ref (+ i 3)) 10) do
        (let ((j (* 4 (+ (min (1- sw) (floor (* (+ x .5d0) (/ sw w))))
                         (* sw (min (1- sh) (floor (* (+ y .5d0) (/ sh h)))))))))
          (dotimes (c 3) (setf (aref out (+ i c)) (aref src (+ j c))))
          (setf (aref out (+ i 3)) 255)))) out))
