(load "lisp/assets/images.lisp")
(in-package :maw-tools)
(defun food-json (path data) (write-text (concatenate 'string "src/main/resources/" path) (encode data t)))
(defun food-recipe (name ingredients count)
  (food-json (format nil "data/the_four_primitives_and_weapons/recipes/~A.json" name)
    (object "type" "minecraft:crafting_shapeless" "ingredients" (coerce (mapcar (lambda (id) (object "item" id)) ingredients) 'vector)
      "result" (object "item" (format nil "the_four_primitives_and_weapons:~A" name) "count" count))))
(defun food-assets ()
  (let* ((args (uiop:command-line-arguments))
         (jar (if (and (= (length args) 2) (equal (first args) "--vanilla-jar")) (pathname (second args))
                  (if (null args) (merge-pathnames ".gradle/caches/forge_gradle/minecraft_repo/versions/1.20.1/client.jar" (user-homedir-pathname)) (error "--vanilla-jar client.jar"))))
         (temp (merge-pathnames (format nil "maw-food-~D-~D/" (get-universal-time) (random 1000000000 (make-random-state t))) (uiop:temporary-directory)))
         (textures '(("item/kinmokusei_flowers" "block/dandelion" :gold)
                     ("item/kinmokusei_syrup" "item/honey_bottle" :gold)
                     ("item/kinmokusei_cookie" "item/cookie" :gold)
                     ("item/kinmokusei_cake" "item/cake" :cake)
                     ("block/kinmokusei_cake_top" "block/cake_top" :cake)
                     ("block/kinmokusei_cake_side" "block/cake_side" :cake)
                     ("block/kinmokusei_cake_inner" "block/cake_inner" :cake))))
    (unless (probe-file jar) (error "バニラのclient.jarがありません"))
    (when (probe-file temp) (error "一時保存先が既存です"))
    (unwind-protect
      (progn
        (ensure-directories-exist (merge-pathnames "placeholder" temp))
        (uiop:run-program (append (list "unzip" "-q" "-j" (namestring jar))
          (mapcar (lambda (entry) (format nil "assets/minecraft/textures/~A.png" (second entry))) textures) (list "-d" (namestring temp))))
        (dolist (entry textures)
          (destructuring-bind (output source mode) entry
            (multiple-value-bind (pixels w h) (image-load (namestring (merge-pathnames (file-namestring (pathname (concatenate 'string source ".png"))) temp)))
              (loop for i from 0 below (length pixels) by 4
                for r = (aref pixels i) for g = (aref pixels (+ i 1)) for b = (aref pixels (+ i 2))
                when (and (> (aref pixels (+ i 3)) 0)
                     (if (eq mode :cake) (> r (* 1.3 (max 1 g))) (and (> r g) (> g b)))) do
                  (let ((light (max 0.3 (/ r 255d0))))
                    (setf (aref pixels i) (round (* 250 light)) (aref pixels (+ i 1)) (round (* 171 light)) (aref pixels (+ i 2)) (round (* 49 light)))))
              (image-save (format nil "src/main/resources/assets/the_four_primitives_and_weapons/textures/~A.png" output) pixels w h)))))
      (uiop:delete-directory-tree temp :validate t :if-does-not-exist :ignore)))
  (dolist (name '("kinmokusei_flowers" "kinmokusei_syrup" "kinmokusei_cookie" "kinmokusei_cake"))
    (food-json (format nil "assets/the_four_primitives_and_weapons/models/item/~A.json" name)
      (object "parent" "minecraft:item/generated" "textures" (object "layer0" (format nil "the_four_primitives_and_weapons:item/~A" name)))))
  (let ((variants (object)))
    (dotimes (bite 7)
      (let ((name (format nil "kinmokusei_cake~A" (if (zerop bite) "" (format nil "_slice~D" bite)))))
        (setf (gethash (format nil "bites=~D" bite) variants) (object "model" (format nil "the_four_primitives_and_weapons:block/~A" name)))
        (food-json (format nil "assets/the_four_primitives_and_weapons/models/block/~A.json" name)
          (object "parent" (format nil "minecraft:block/cake~A" (if (zerop bite) "" (format nil "_slice~D" bite)))
            "textures" (object "top" "the_four_primitives_and_weapons:block/kinmokusei_cake_top"
              "side" "the_four_primitives_and_weapons:block/kinmokusei_cake_side" "inside" "the_four_primitives_and_weapons:block/kinmokusei_cake_inner"
              "particle" "the_four_primitives_and_weapons:block/kinmokusei_cake_side" "bottom" "minecraft:block/cake_bottom")))))
    (food-json "assets/the_four_primitives_and_weapons/blockstates/kinmokusei_cake.json" (object "variants" variants)))
  (food-json "data/the_four_primitives_and_weapons/loot_tables/blocks/kinmokusei_cake.json" (object "type" "minecraft:block" "pools" #()))
  (food-recipe "kinmokusei_syrup" '("the_four_primitives_and_weapons:kinmokusei_flowers" "the_four_primitives_and_weapons:kinmokusei_flowers" "the_four_primitives_and_weapons:kinmokusei_flowers" "minecraft:sugar" "minecraft:sugar" "minecraft:glass_bottle" "minecraft:water_bucket") 1)
  (food-recipe "kinmokusei_cake" '("minecraft:cake" "the_four_primitives_and_weapons:kinmokusei_syrup") 1)
  (food-recipe "kinmokusei_cookie" '("minecraft:wheat" "minecraft:wheat" "the_four_primitives_and_weapons:kinmokusei_syrup") 8)
  (dolist (name '("kinmokusei_syrup" "kinmokusei_cake" "kinmokusei_cookie"))
    (food-json (format nil "data/the_four_primitives_and_weapons/advancements/recipes/food/~A.json" name)
      (object "parent" "minecraft:recipes/root" "criteria" (object "has_ingredient" (object "trigger" "minecraft:inventory_changed"
        "conditions" (object "items" (vector (object "items" (vector (format nil "the_four_primitives_and_weapons:~A" (if (equal name "kinmokusei_syrup") "kinmokusei_flowers" "kinmokusei_syrup"))))))))
        "rewards" (object "recipes" (vector (format nil "the_four_primitives_and_weapons:~A" name))))))
  (loop for lang in '("ja_jp" "en_us") for names in '(("金木犀の花" "金木犀のシロップ" "金木犀のクッキー" "金木犀のケーキ") ("Osmanthus Flowers" "Osmanthus Syrup" "Osmanthus Cookie" "Osmanthus Cake")) do
    (let* ((path (format nil "src/main/resources/assets/the_four_primitives_and_weapons/lang/~A.json" lang)) (data (parse-json (read-text path))))
      (loop for id in '("kinmokusei_flowers" "kinmokusei_syrup" "kinmokusei_cookie" "kinmokusei_cake") for label in names do
        (setf (gethash (format nil "~A.the_four_primitives_and_weapons.~A" (if (equal id "kinmokusei_cake") "block" "item") id) data) label))
      (write-text path (encode data t)))))
(food-assets)
