(load "lisp/common/core.lisp")
(in-package :maw-tools)
(defparameter *shell-tools*
  '((:run "macOS向け起動・軽量化MOD選択" "sh/run/run_client_mac.sh" "既定はオフライン。online / offline / notls / tls / keepdaemon")
    (:run "共通クライアント起動" "sh/run/run_client.sh" "既定はオンライン。offlineでキャッシュを使用")
    (:run "WSLからWindows版を起動" "sh/run/run_client_win.sh" "Windows側Javaと設定済みプロジェクトパスが必要。offline対応")
    (:build "共通ビルド・バージョン指定" "sh/build/build.sh" "clean / offline / -Pmod_version_override=... / -Prelease_type=...")
    (:build "macOS向けビルド" "sh/build/build_mac.sh" "clean / offline。出力先はbuild/libs")
    (:build "WSLからWindows版をビルド" "sh/build/build_win.sh" "cleanのみ対応。Windows側の固定パスを使用")
    (:generate "汎用Lispからデータパック生成" "sh/generate/generate-mcfunction.sh" "MOD不要。独立したtools/mcfunction-lispを他repoでも使用可能")
    (:generate "蝶・刀のコマンドを対話式で生成" "sh/generate/generate_commands.sh" "49種類の蝶、拵え、設置角度などを設定。SBCLが必要")
    (:generate "ランダム地形の撮影ワールドを作成" "sh/generate/generate-photo-world.sh" "Lisp→mcfunction。毎回別の地形、シード指定で再現。SBCL・gzip・zip")
    (:generate "テクスチャ・ノイズフォントを生成" "sh/generate/generate-assets.sh" "SBCL・Java 17。Lispで画素を加工")
    (:maintenance "Javaのlevel参照を移行" "sh/maintenance/codemod-level.sh" "既定は候補表示、--applyでバックアップ付き適用")
    (:maintenance "MCreatorのコードをロック" "sh/maintenance/lock_codes.sh" "通常ロック / --allでベース設定とバックアップも処理")
    (:maintenance "外部MOD・シェーダーを同期" "sh/maintenance/sync-selected-external-mods.sh" "--performance-only / --light / --offline。libs/runtime_selectedを更新")
    (:test "通信軽量化を検証" "sh/test/test-performance.sh" "Java 17。重複送信の抑制と再同期を検証")
    (:test "ランダム撮影地形を検証" "sh/test/test-photo-terrain.sh" "SBCL。シード再現・地形の傾斜・植生を検証")
    (:test "Lisp移植した画像・修正ツールを検証" "sh/test/test-lisp-migration.sh" "SBCL・Java 17。PNG入出力と画素処理を検証")
    (:test "Lisp製ツールを検証" "sh/test/test-lisp-tools.sh" "SBCL。JSON・コマンド生成・ロックのテスト")
    (:test "忍者刀の伝導処理を検証" "sh/test/test-ninjato-conduction.sh" "Javaの小規模テスト")
    (:test "忍者刀の鎖切断を検証" "sh/test/test-ninjato-tether-cut.sh" "Javaの小規模テスト")
    (:test "忍者刀の跳躍操作を検証" "sh/test/test-ninjato-vault.sh" "Javaの小規模テスト")
    (:test "武器ラック表示を検証" "sh/test/test-rack-display.sh" "Gradleと依存キャッシュが必要。コンパイルを伴う")
    (:test "刺した武器の形状を検証" "sh/test/test-stabbed-weapon-geometry.sh" "Gradleと依存キャッシュが必要。コンパイルを伴う")))
(defun shell-comment-help (path)
  ;; Read comments; never invoke a target's help, since some targets are tests.
  (loop for line in (cdr (uiop:split-string (read-text path) :separator '(#\Newline)))
        while (or (equal (string-trim '(#\Space #\Tab) line) "")
                  (and (> (length line) 0) (char= (char line 0) #\#)))
        do (format t "~A~%" (if (and (> (length line) 0) (char= (char line 0) #\#))
                                (string-left-trim '(#\Space) (subseq line 1)) line))))
(defun shell-help (tool)
  (destructuring-bind (group title path summary) tool
    (declare (ignore group))
    (format t "~%~A~%  bash ~A~%  ~A~%" title path summary)
    (shell-comment-help path)))
(defun all-help (&optional detailed)
  (format t "sh全体のヘルプ~%~%")
  (shell-comment-help "sh/menu.sh")
  (terpri)
  (dolist (group '(:run :build :generate :maintenance :test))
    (format t "~A~%" (case group (:run "ゲーム起動") (:build "ビルド") (:generate "コマンド生成") (:maintenance "保守") (:test "検証")))
    (dolist (tool *shell-tools*)
      (when (eq group (first tool))
        (if detailed (shell-help tool)
          (format t "  ~A~%    bash ~A~%    ~A~%" (second tool) (third tool) (fourth tool)))))))
(defun select-tool (group)
  (let* ((tools (remove-if-not (lambda (entry) (eq group (first entry))) *shell-tools*))
         (i (choose "どの処理を使いますか？" (append (mapcar #'second tools) '("戻る")))))
    (when (< i (length tools)) (nth i tools))))
(defun task-arguments (tool)
  (let ((path (third tool)))
    (cond
      ((equal path "sh/run/run_client_mac.sh")
       (nth (choose "どう起動しますか？" '("オフライン" "オンライン・TLS自動判定" "オンライン・TLS制限なし" "オフライン・daemon維持"))
            '(("offline") ("online") ("online" "notls") ("offline" "keepdaemon"))))
      ((equal path "sh/generate/generate-mcfunction.sh")
       (list "--source" (prompt "Lispソース" "tools/mcfunction-lisp/examples/terrain.lisp")
             "--output" (prompt "新規データパック保存先" (format nil "run/generated_commands/datapack-~D" (get-universal-time)))
             "--namespace" (prompt "名前空間" "demo")))
      ((equal path "sh/generate/generate-photo-world.sh")
       (let ((seed (prompt "地形シード（randomで毎回変更）" "random")))
         (append (list "--world" (prompt "新しい保存先" (format nil "run/saves/刀の庭園-~D" (get-universal-time))))
                 (unless (equal seed "random") (list "--seed" seed)))))
      ((equal path "sh/generate/generate-assets.sh")
       (if (= 0 (choose "生成したいもの" '("拵えテクスチャ" "ノイズフォント")))
           (list "fit" (prompt "素材画像のパス") (prompt "部位" "tuka") (prompt "出力名" "custom_tuka")
                 "--weapon" (nth (choose "武器種" '("katana" "tyokuto" "rapier")) '("katana" "tyokuto" "rapier")))
           (list "noise")))
      ((equal path "sh/maintenance/codemod-level.sh")
       (if (yes "バックアップを作成して変更を適用しますか？") '("--apply") nil))
      ((eq (first tool) :run)
       (nth (choose "どう起動しますか？" '("オンライン" "オフライン")) '(nil ("offline"))))
      ((equal path "sh/build/build_win.sh")
       (nth (choose "ビルド方法" '("通常" "クリーンビルド")) '(nil ("clean"))))
      ((eq (first tool) :build)
       (nth (choose "ビルド方法" '("通常" "オフライン" "クリーン" "クリーン＋オフライン"))
            '(nil ("offline") ("clean") ("clean" "offline"))))
      ((equal path "sh/maintenance/lock_codes.sh")
       (nth (choose "ロック方法" '("要素のコードをロック" "ベース設定・マーカー・バックアップも処理")) '(nil ("--all"))))
      ((equal path "sh/maintenance/sync-selected-external-mods.sh")
       (let ((args (nth (choose "同期するMOD" '("軽量化MODのみ" "軽量化＋追加機能MOD" "重いMODも含める"))
                        '(("--performance-only") ("--light") nil))))
         (append args (nth (choose "接続方法" '("オフライン" "通常")) '(("--offline") nil)))))
      (t nil))))
(defun execute-tool (tool dry-run)
  (let ((args (task-arguments tool)))
    (format t "~%実行コマンド: bash ~A~{ ~A~}~%" (third tool) args)
    (unless dry-run
      (let ((code (nth-value 2 (uiop:run-program (append (list "bash" (third tool)) args)
                     :input :interactive :output :interactive :error-output :interactive :ignore-error-status t))))
        (unless (eql code 0) (format t "処理が終了コード~Aで終了しました。メニューに戻ります。~%" code))))))
(defun menu-main ()
  (let ((args (uiop:command-line-arguments)))
    (when (some (lambda (s) (member s '("help" "--help" "-h") :test #'equal)) args)
      (let* ((name (find-if (lambda (s) (not (member s '("help" "--help" "-h" "--all") :test #'equal))) args))
             (tool (and name (find name *shell-tools* :key #'third :test #'equal))))
        (cond (tool (shell-help tool)) (name (error "一覧にないshです: ~A" name))
              (t (all-help (member "--all" args :test #'equal)))))
      (return-from menu-main))
    (dolist (arg args) (unless (equal arg "--dry-run") (error "未対応の引数: ~A" arg)))
    (loop for choice = (choose "何をしたいですか？"
                       '("ゲームを起動したい" "MODのJARを作りたい" "蝶や刀を生成したい" "MOD同期・コードロックをしたい" "動作を検証したい" "全体のヘルプ・使い方を読みたい" "終了"))
          until (= choice 6) do
      (if (= choice 5)
          (progn (all-help)
            (let ((i (choose "詳しい説明を読む" (append (mapcar #'second *shell-tools*) '("戻る")) (length *shell-tools*))))
              (when (< i (length *shell-tools*)) (shell-help (nth i *shell-tools*)))))
          (let ((tool (select-tool (nth choice '(:run :build :generate :maintenance :test)))))
            (when tool
              (case (choose "次の操作" '("実行する" "使い方を読む" "戻る"))
                (0 (execute-tool tool (member "--dry-run" args :test #'equal)))
                (1 (shell-help tool)))))))))
(run-tool #'menu-main)
