(load "lisp/common/core.lisp")
(in-package :maw-tools)
(defparameter *shell-tools*
  '((:run "macOS向け起動・軽量化MOD選択" "sh/run/run_client_mac.sh" "既定はオフライン。online / offline / notls / tls / keepdaemon")
    (:run "共通クライアント起動" "sh/run/run_client.sh" "既定はオンライン。offlineでキャッシュを使用")
    (:run "WSLからWindows版を起動" "sh/run/run_client_win.sh" "Windows側Javaと設定済みプロジェクトパスが必要。offline対応")
    (:build "共通ビルド・バージョン指定" "sh/build/build.sh" "clean / offline / -Pmod_version_override=... / -Prelease_type=...")
    (:build "macOS向けビルド" "sh/build/build_mac.sh" "clean / offline。出力先はbuild/libs")
    (:build "WSLからWindows版をビルド" "sh/build/build_win.sh" "cleanのみ対応。Windows側の固定パスを使用")
    (:generate "蝶・刀のコマンドを対話式で生成" "sh/generate/generate_commands.sh" "48種類の蝶、拵え、設置角度などを設定。SBCLが必要")
    (:maintenance "MCreatorのコードをロック" "sh/maintenance/lock_codes.sh" "通常ロック / --allでベース設定とバックアップも処理")
    (:maintenance "外部MOD・シェーダーを同期" "sh/maintenance/sync-selected-external-mods.sh" "--performance-only / --light / --offline。libs/runtime_selectedを更新")
    (:test "Lisp製ツールを検証" "sh/test/test-lisp-tools.sh" "SBCL。JSON・コマンド生成・ロックのテスト")
    (:test "忍者刀の伝導処理を検証" "sh/test/test-ninjato-conduction.sh" "Javaの小規模テスト")
    (:test "忍者刀の鎖切断を検証" "sh/test/test-ninjato-tether-cut.sh" "Javaの小規模テスト")
    (:test "忍者刀の跳躍操作を検証" "sh/test/test-ninjato-vault.sh" "Javaの小規模テスト")
    (:test "武器ラック表示を検証" "sh/test/test-rack-display.sh" "Gradleと依存キャッシュが必要。コンパイルを伴う")
    (:test "刺した武器の形状を検証" "sh/test/test-stabbed-weapon-geometry.sh" "Gradleと依存キャッシュが必要。コンパイルを伴う")))
(defun shell-help (tool)
  (destructuring-bind (group title path summary) tool
    (declare (ignore group))
    (format t "~%~A~%  bash ~A~%  ~A~%" title path summary)
    ;; Read comments; never invoke a target's help, since some targets are tests.
    (loop for line in (cdr (uiop:split-string (read-text path) :separator '(#\Newline)))
          while (or (equal (string-trim '(#\Space #\Tab) line) "")
                    (and (> (length line) 0) (char= (char line 0) #\#)))
          do (format t "~A~%" (if (and (> (length line) 0) (char= (char line 0) #\#))
                                  (string-left-trim '(#\Space) (subseq line 1)) line)))))
(defun all-help (&optional detailed)
  (format t "sh全体のヘルプ~%~%対話式: bash sh/menu.sh~%一覧: bash sh/menu.sh help~%全文: bash sh/menu.sh help --all~%個別: bash sh/menu.sh help sh/generate/generate_commands.sh~%実行せず選択内容を確認: bash sh/menu.sh --dry-run~%~%")
  (dolist (group '(:run :build :generate :maintenance :test))
    (format t "~A~%" (case group (:run "ゲーム起動") (:build "ビルド") (:generate "コマンド生成") (:maintenance "保守") (:test "検証")))
    (dolist (tool *shell-tools*)
      (when (eq group (first tool))
        (if detailed (shell-help tool)
          (format t "  ~A~%    bash ~A~%    ~A~%" (second tool) (third tool) (fourth tool)))))))
(defun select-tool (group)
  (let* ((tools (remove-if-not (lambda (entry) (eq group (first entry))) *shell-tools*))
         (i (choose "どの処理を使いますか？" (append (mapcar #'second tools) '("戻る")))))
    (when (< i (length tools)) (nth i tools))))
(defun task-arguments (tool)
  (let ((path (third tool)))
    (cond
      ((equal path "sh/run/run_client_mac.sh")
       (nth (choose "どう起動しますか？" '("オフライン" "オンライン・TLS自動判定" "オンライン・TLS制限なし" "オフライン・daemon維持"))
            '(("offline") ("online") ("online" "notls") ("offline" "keepdaemon"))))
      ((eq (first tool) :run)
       (nth (choose "どう起動しますか？" '("オンライン" "オフライン")) '(nil ("offline"))))
      ((equal path "sh/build/build_win.sh")
       (nth (choose "ビルド方法" '("通常" "クリーンビルド")) '(nil ("clean"))))
      ((eq (first tool) :build)
       (nth (choose "ビルド方法" '("通常" "オフライン" "クリーン" "クリーン＋オフライン"))
            '(nil ("offline") ("clean") ("clean" "offline"))))
      ((equal path "sh/maintenance/lock_codes.sh")
       (nth (choose "ロック方法" '("要素のコードをロック" "ベース設定・マーカー・バックアップも処理")) '(nil ("--all"))))
      ((equal path "sh/maintenance/sync-selected-external-mods.sh")
       (let ((args (nth (choose "同期するMOD" '("軽量化MODのみ" "軽量化＋追加機能MOD" "重いMODも含める"))
                        '(("--performance-only") ("--light") nil))))
         (append args (nth (choose "接続方法" '("オフライン" "通常")) '(("--offline") nil)))))
      (t nil))))
(defun execute-tool (tool dry-run)
  (let ((args (task-arguments tool)))
    (format t "~%実行コマンド: bash ~A~{ ~A~}~%" (third tool) args)
    (unless dry-run
      (let ((code (nth-value 2 (uiop:run-program (append (list "bash" (third tool)) args)
                     :input :interactive :output :interactive :error-output :interactive :ignore-error-status t))))
        (unless (eql code 0) (format t "処理が終了コード~Aで終了しました。メニューに戻ります。~%" code))))))
(defun menu-main ()
  (let ((args (uiop:command-line-arguments)))
    (when (some (lambda (s) (member s '("help" "--help" "-h") :test #'equal)) args)
      (let* ((name (find-if (lambda (s) (not (member s '("help" "--help" "-h" "--all") :test #'equal))) args))
             (tool (and name (find name *shell-tools* :key #'third :test #'equal))))
        (cond (tool (shell-help tool)) (name (error "一覧にないshです: ~A" name))
              (t (all-help (member "--all" args :test #'equal)))))
      (return-from menu-main))
    (dolist (arg args) (unless (equal arg "--dry-run") (error "未対応の引数: ~A" arg)))
    (loop for choice = (choose "何をしたいですか？"
                       '("ゲームを起動したい" "MODのJARを作りたい" "蝶や刀を生成したい" "MOD同期・コードロックをしたい" "動作を検証したい" "全体のヘルプ・使い方を読みたい" "終了"))
          until (= choice 6) do
      (if (= choice 5)
          (progn (all-help)
            (let ((i (choose "詳しい説明を読む" (append (mapcar #'second *shell-tools*) '("戻る")) (length *shell-tools*))))
              (when (< i (length *shell-tools*)) (shell-help (nth i *shell-tools*)))))
          (let ((tool (select-tool (nth choice '(:run :build :generate :maintenance :test)))))
            (when tool
              (case (choose "次の操作" '("実行する" "使い方を読む" "戻る"))
                (0 (execute-tool tool (member "--dry-run" args :test #'equal)))
                (1 (shell-help tool)))))))))
(run-tool #'menu-main)
