;;; Preserve model JSON and UVs; mark existing guard/blade faces for dynamic 3D fittings.
(defun read-text (path)
  (with-open-file (in path)
    (let* ((s (make-string (file-length in))) (count (read-sequence s in)))
      (string-right-trim '(#\Null) (subseq s 0 count)))))
(defun element-ranges (s)
  (let* ((key (search "\"elements\"" s)) (start (and key (position #\[ s :start key))))
    (when start
      (let ((array-depth 1) (object-depth 0) (quote-p nil) (escape-p nil) (object-start nil) (ranges nil))
        (loop for i from (1+ start) below (length s) for c = (char s i) do
          (cond (escape-p (setf escape-p nil))
                ((and quote-p (char= c #\\)) (setf escape-p t))
                ((char= c #\") (setf quote-p (not quote-p)))
                (quote-p)
                ((char= c #\[) (incf array-depth))
                ((char= c #\]) (decf array-depth) (when (= array-depth 0) (return)))
                ((char= c #\{) (when (= object-depth 0) (setf object-start i)) (incf object-depth))
                ((char= c #\}) (decf object-depth) (when (= object-depth 0) (push (cons object-start (1+ i)) ranges)))))
        (nreverse ranges)))))
(defun coordinates (s key)
  (let* ((key-pos (search key s)) (start (and key-pos (position #\[ s :start key-pos)))
         (end (and start (position #\] s :start start))))
    (when end (read-from-string (concatenate 'string "(" (substitute #\Space #\, (subseq s (1+ start) end)) ")")))))
(defun tag-faces (s tint)
  (with-output-to-string (out)
    (loop with start = 0 for pos = (search "\"texture\"" s :start2 start) do
      (unless pos (write-string (subseq s start) out) (return))
      (write-string (subseq s start pos) out)
      (format out "\"tintindex\":~a," tint)
      (write-string "\"texture\"" out)
      (setf start (+ pos 9)))))
(defun patch-model (path)
  (let* ((s (read-text path)) (changed 0)
         (result (with-output-to-string (out)
          (let ((cursor 0))
            (dolist (range (element-ranges s))
              (write-string (subseq s cursor (car range)) out)
              (let* ((element (subseq s (car range) (cdr range))) (from (coordinates element "\"from\"")) (to (coordinates element "\"to\""))
                     (tint (when (and from to (not (search "\"tintindex\"" element)))
                       (cond ((and (>= (second from) 7.7) (<= (second to) 8.6)
                                   (< (- (second to) (second from)) 1)
                                   (> (- (first to) (first from)) .7) (> (- (third to) (third from)) .7)) 2)
                             ((and (>= (second from) 8) (> (- (second to) (second from)) .1)) 6)))))
                (when tint (incf changed))
                (write-string (if tint (tag-faces element tint) element) out))
              (setf cursor (cdr range)))
            (write-string (subseq s cursor) out)))))
    (with-open-file (out path :direction :output :if-exists :supersede) (write-string result out))
    (format t "~a: ~a elements tagged~%" path changed)))
(dolist (name '("weapon/katana/katana_b_parent" "swordb" "swordb2" "kurikarakatana3d" "katananiguzyouwankotu3d"))
  (patch-model (format nil "src/main/resources/assets/the_four_primitives_and_weapons/models/custom/~a.json" name)))
