;;; Generates progression resources without external dependencies. Run with SBCL.
(defun write-text (path text)
  (ensure-directories-exist path)
  (with-open-file (out path :direction :output :if-exists :supersede) (write-string text out)))
(defun read-text (path)
  (with-open-file (in path) (let* ((s (make-string (file-length in))) (n (read-sequence s in))) (subseq s 0 n))))
(defun add-entries (path entries)
  (let* ((s (read-text path)) (end (position #\} s :from-end t))
         (missing (remove-if (lambda (entry) (search (format nil "~s:" (first entry)) s)) entries)))
    (when missing
      (write-text path (with-output-to-string (out)
        (write-string (string-right-trim '(#\Newline #\Return #\Space) (subseq s 0 end)) out)
        (loop for (key value) in missing do (format out ",~%  ~s: ~s" key value))
        (format out "~%}~%"))))))
(dolist (item '("weapon_upgrade_journal" "tempering_shard"))
  (write-text (format nil "src/main/resources/assets/the_four_primitives_and_weapons/models/item/~a.json" item)
    (format nil "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:item/~a\"}}"
      (if (string= item "tempering_shard") "amethyst_shard" "book"))))
(write-text "src/main/resources/data/the_four_primitives_and_weapons/recipes/weapon_upgrade_journal.json"
 "{\"type\":\"minecraft:crafting_shapeless\",\"ingredients\":[{\"item\":\"minecraft:paper\"},{\"item\":\"minecraft:emerald\"},{\"item\":\"minecraft:iron_ingot\"}],\"result\":{\"item\":\"the_four_primitives_and_weapons:weapon_upgrade_journal\"}}")
(let ((jp '(("item.the_four_primitives_and_weapons.weapon_upgrade_journal" "武器育成手帳")
 ("item.the_four_primitives_and_weapons.tempering_shard" "鍛錬の欠片")
 ("tooltip.the_four_primitives_and_weapons.upgrade_journal" "右クリックで武器を強化・能力を選択。敵を倒して武器を育てよう。")
 ("tooltip.the_four_primitives_and_weapons.growth_hint" "武器育成手帳から強化・能力選択ができる（武器は1個ずつ育成）")
 ("tooltip.the_four_primitives_and_weapons.tempering_shard" "武器で敵を倒すと入手。強化と能力の振り直しに使用。")
 ("tooltip.the_four_primitives_and_weapons.growth_power" "強化による威力：＋%s%%")
 ("message.the_four_primitives_and_weapons.upgrade_requirements" "必要な武器レベル・能力ポイントを確認してください")
 ("message.the_four_primitives_and_weapons.upgrade_materials" "エメラルドか鍛錬の欠片が足りません")
 ("message.the_four_primitives_and_weapons.weapon_level_up" "%s の武器レベルが %s になりました")
 ("gui.the_four_primitives_and_weapons.upgrade.title" "武器育成")
 ("gui.the_four_primitives_and_weapons.upgrade.back" "戻る")
 ("gui.the_four_primitives_and_weapons.upgrade.power" "強化")
 ("gui.the_four_primitives_and_weapons.upgrade.power_next" "＋%sへ強化（武器Lv.%s以上）")
 ("gui.the_four_primitives_and_weapons.upgrade.power_max" "強化上限 ＋20")
 ("gui.the_four_primitives_and_weapons.upgrade.reset" "能力を振り直す")
 ("gui.the_four_primitives_and_weapons.upgrade.reset_cost" "エメラルド5個＋鍛錬の欠片3個。能力ポイントをすべて返却。武器レベルと強化値は維持。")
 ("gui.the_four_primitives_and_weapons.upgrade.slot" "能力%s：%s [%s/3]")
 ("gui.the_four_primitives_and_weapons.upgrade.slot_locked" "能力%s：武器Lv.%sで解放")
 ("gui.the_four_primitives_and_weapons.upgrade.choose" "選択")
 ("gui.the_four_primitives_and_weapons.upgrade.point_cost" "次の段階：能力ポイント%s（1→2→3）")
 ("gui.the_four_primitives_and_weapons.upgrade.no_weapon" "育成する武器を1個持ってください")
 ("gui.the_four_primitives_and_weapons.upgrade.status" "武器Lv.%s/%s　強化＋%s　残りポイント%s")
 ("gui.the_four_primitives_and_weapons.upgrade.cost" "必要：エメラルド%s個・鍛錬の欠片%s個")
 ("gui.the_four_primitives_and_weapons.upgrade.owned" "所持：エメラルド%s個・鍛錬の欠片%s個")
 ("gui.the_four_primitives_and_weapons.upgrade.xp" "武器経験値 %s / %s")
 ("gui.the_four_primitives_and_weapons.upgrade.level_max" "武器レベル上限到達")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.power" "剛力")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.power.desc" "1段階につき与えるダメージ＋5%")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.precision" "会心")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.precision.desc" "1段階につき8%の確率でダメージが1.5倍")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.leech" "吸命")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.leech.desc" "敵への命中で1段階につき体力0.25を吸収。最大でも与ダメージの15%、1秒に1回。")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.haste" "迅撃")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.haste.desc" "1段階につき攻撃速度＋6%。弓・クロスボウの溜め時間も短縮。")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.breaker" "破勢")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.breaker.desc" "1段階につき近接攻撃の体勢崩し＋20%")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.guard" "守勢")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.guard.desc" "1段階につきガード中に受けるダメージをさらに6%軽減")))
 (en '(("item.the_four_primitives_and_weapons.weapon_upgrade_journal" "Weapon Growth Journal")
 ("item.the_four_primitives_and_weapons.tempering_shard" "Tempering Shard")
 ("tooltip.the_four_primitives_and_weapons.upgrade_journal" "Right-click to upgrade weapons and choose traits. Defeat enemies to grow your weapon.")
 ("tooltip.the_four_primitives_and_weapons.growth_hint" "Use a Weapon Growth Journal to upgrade or select traits. Weapons grow individually.")
 ("tooltip.the_four_primitives_and_weapons.tempering_shard" "Obtained by defeating enemies with a weapon. Used for upgrades and trait resets.")
 ("tooltip.the_four_primitives_and_weapons.growth_power" "Upgrade damage: +%s%%")
 ("message.the_four_primitives_and_weapons.upgrade_requirements" "Check the required weapon level and trait points")
 ("message.the_four_primitives_and_weapons.upgrade_materials" "Not enough emeralds or tempering shards")
 ("message.the_four_primitives_and_weapons.weapon_level_up" "%s reached weapon level %s")
 ("gui.the_four_primitives_and_weapons.upgrade.title" "Weapon Growth")
 ("gui.the_four_primitives_and_weapons.upgrade.back" "Back")
 ("gui.the_four_primitives_and_weapons.upgrade.power" "Upgrade")
 ("gui.the_four_primitives_and_weapons.upgrade.power_next" "Upgrade to +%s (weapon Lv.%s required)")
 ("gui.the_four_primitives_and_weapons.upgrade.power_max" "Maximum upgrade +20")
 ("gui.the_four_primitives_and_weapons.upgrade.reset" "Reset traits")
 ("gui.the_four_primitives_and_weapons.upgrade.reset_cost" "5 emeralds + 3 tempering shards. Refunds all trait points; preserves level and upgrades.")
 ("gui.the_four_primitives_and_weapons.upgrade.slot" "Trait %s: %s [%s/3]")
 ("gui.the_four_primitives_and_weapons.upgrade.slot_locked" "Trait %s: unlocks at weapon Lv.%s")
 ("gui.the_four_primitives_and_weapons.upgrade.choose" "Choose")
 ("gui.the_four_primitives_and_weapons.upgrade.point_cost" "Next rank: %s trait points (1, then 2, then 3)")
 ("gui.the_four_primitives_and_weapons.upgrade.no_weapon" "Carry one weapon to grow")
 ("gui.the_four_primitives_and_weapons.upgrade.status" "Weapon Lv.%s/%s  Upgrade +%s  Points %s")
 ("gui.the_four_primitives_and_weapons.upgrade.cost" "Cost: %s emeralds, %s tempering shards")
 ("gui.the_four_primitives_and_weapons.upgrade.owned" "Owned: %s emeralds, %s tempering shards")
 ("gui.the_four_primitives_and_weapons.upgrade.xp" "Weapon XP %s / %s")
 ("gui.the_four_primitives_and_weapons.upgrade.level_max" "Maximum weapon level")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.power" "Might")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.power.desc" "+5% damage per rank")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.precision" "Critical")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.precision.desc" "8% chance per rank to deal 1.5x damage")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.leech" "Leech")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.leech.desc" "Heal 0.25 health per rank on enemy hits, capped at 15% of damage, once per second.")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.haste" "Haste")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.haste.desc" "+6% attack speed per rank; faster bow and crossbow charging.")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.breaker" "Breaker")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.breaker.desc" "+20% melee posture impact per rank")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.guard" "Guard")
 ("gui.the_four_primitives_and_weapons.upgrade.perk.guard.desc" "Reduce remaining damage while guarding by 6% per rank"))))
 (add-entries "src/main/resources/assets/the_four_primitives_and_weapons/lang/ja_jp.json" jp)
 (add-entries "src/main/resources/assets/the_four_primitives_and_weapons/lang/en_us.json" en))
