(load "lisp/common/core.lisp")
(in-package :maw-tools)
(defun identifier-char-p (c) (or (alphanumericp c) (find c "_$")))
(defun migrate-level (source)
  (let ((i 0) (n (length source)) (quote-char nil) (line-comment nil) (block-comment nil))
    (with-output-to-string (out)
      (loop while (< i n) for c = (char source i) for next = (when (< (1+ i) n) (char source (1+ i))) do
        (cond
          (line-comment (write-char c out) (when (char= c #\Newline) (setf line-comment nil)) (incf i))
          (block-comment (write-char c out) (incf i) (when (and (char= c #\*) (eql next #\/)) (write-char next out) (incf i) (setf block-comment nil)))
          (quote-char (write-char c out) (incf i)
            (cond ((and (char= c #\\) (< i n)) (write-char (char source i) out) (incf i))
                  ((char= c quote-char) (setf quote-char nil))))
          ((and (char= c #\/) (eql next #\/)) (write-string "//" out) (incf i 2) (setf line-comment t))
          ((and (char= c #\/) (eql next #\*)) (write-string "/*" out) (incf i 2) (setf block-comment t))
          ((find c '(#\" #\')) (setf quote-char c) (write-char c out) (incf i))
          ((and (char= c #\.) (<= (+ i 6) n) (string= source ".level" :start1 i :end1 (+ i 6))
                (> i 0) (identifier-char-p (char source (1- i)))
                (or (= (+ i 6) n) (not (identifier-char-p (char source (+ i 6))))))
           (let* ((after (+ i 6)) (j after)
                  (start (1+ (or (position #\Newline source :end i :from-end t) -1)))
                  (prefix (string-left-trim '(#\Space #\Tab) (subseq source start i))))
             (loop while (and (< j n) (find (char source j) '(#\Space #\Tab #\Newline #\Return))) do (incf j))
             (write-string ".level" out)
             (unless (or (and (< j n) (char= (char source j) #\())
                         (uiop:string-prefix-p "import " prefix) (uiop:string-prefix-p "package " prefix))
               (write-string "()" out)) (setf i after)))
          (t (write-char c out) (incf i)))))))
(defun java-files (dir)
  (append (remove-if-not (lambda (p) (equal (pathname-type p) "java")) (uiop:directory-files dir))
          (mapcan #'java-files (uiop:subdirectories dir))))
(defun codemod-main ()
  (let* ((args (uiop:command-line-arguments)) (apply-p (member "--apply" args :test #'equal))
         (root (uiop:ensure-directory-pathname (or (find-if (lambda (s) (not (uiop:string-prefix-p "--" s))) args) "src/"))) (count 0))
    (dolist (file (java-files root))
      (let* ((old (read-text file)) (new (migrate-level old)))
        (unless (equal old new)
          (incf count) (format t "~A~%" file)
          (when apply-p
            (let ((backup (concatenate 'string (namestring file) ".bak")))
              (when (probe-file backup) (error "既存バックアップを保護: ~A" backup))
              (write-text backup old) (write-text file new))))))
    (format t "~Dファイル ~A~%" count (if apply-p "更新" "候補のみ表示 (--applyで適用)"))))
(unless (member "--test" (uiop:command-line-arguments) :test #'equal) (run-tool #'codemod-main))
