(load "lisp/common/core.lisp")
(in-package :maw-tools)
(defun lock-workspace (path &optional all)
  (let* ((source (read-text path)) (data (parse-json source))
         (elements (gethash "mod_elements" data)) (count 0)
         (backup (if all (format nil "~A.backup_~D" path (get-universal-time)) (concatenate 'string path ".backup_auto"))))
    (unless (and (hash-table-p data) (vectorp elements)) (error "ワークスペース形式を確認してください"))
    (loop for entry across elements do
      (multiple-value-bind (value present) (gethash "locked_code" entry)
        (when (and (or all present) (not (eq value :true)))
          (setf (gethash "locked_code" entry) :true) (incf count))))
    (when all
      (let ((settings (or (gethash "workspaceSettings" data) (object))))
        (setf (gethash "lockBaseModFiles" settings) :true (gethash "workspaceSettings" data) settings)))
    (write-text backup source)
    (write-text path (encode data t))
    (format t "~D要素をロックしました。バックアップ: ~A~%" count backup)))
(defvar *protected-files*)
(defun lock-main ()
  (let* ((args (uiop:command-line-arguments)) (all (member "--all" args :test #'equal))
         (path (or (find-if (lambda (s) (not (uiop:string-prefix-p "--" s))) args)
                   "the_four_primitives_and_weapons.mcreator")))
    (lock-workspace path all)
    (when all
      (dolist (dir '("" "init/" "entity/" "client/init/" "client/renderer/"))
        (write-text (concatenate 'string "src/main/java/the_four_primitives_and_weapons/" dir ".mcreator_lock")
                    "# MCreator Lock File"))
      (load "lisp/maintenance/protected-files.lisp")
      (dolist (file *protected-files*)
        (when (probe-file file)
          (let ((dest (merge-pathnames (file-namestring file) ".protected_custom_files/")))
            (ensure-directories-exist dest) (uiop:copy-file file dest))))
      (let ((ignore (if (probe-file ".gitignore") (read-text ".gitignore") "")))
        (dolist (entry '("**/.mcreator_lock" ".protected_custom_files/" "*.backup_*" "the_four_primitives_and_weapons.mcreator.lock"))
          (unless (search entry ignore) (setf ignore (format nil "~A~%~A~%" ignore entry))))
        (write-text ".gitignore" ignore)))))
(defvar *protected-files*)
(unless (member "--test" (uiop:command-line-arguments) :test #'equal) (run-tool #'lock-main))
